import classes.RoomClass;
import classes.GLOBAL;
import classes.Util.*;
import classes.Engine.Interfaces.*;
import classes.Engine.Utility.*;

//public static const INDOOR:int                                 = 0;
//public static const OUTDOOR:int                                = 1;
//public static const BED:int                                    = 2;
//public static const COMMERCE:int							   = 3;
//public static const BAR:int									   = 4;
//public static const NPC:int									   = 5;
//public static const MEDICAL:int								   = 6;
//public static const SHIPHANGAR:int							   = 7;
//public static const QUEST:int								   = 8;
//public static const OBJECTIVE:int						       = 9;
//public static const HAZARD:int								   = 10;
//public static const NOFAP:int 								   = 11;
//public static const LIFTUP:int 								   = 12;
//public static const LIFTDOWN:int 								= 13;
//public static const TAXI:int    								= 14;
//public static const PUBLIC:int 									= 15;
//public static const PRIVATE:int									= 16;
//public static const FAPPING_ILLEGAL:int							= 17;
//public static const NUDITY_ILLEGAL:int							= 18;
//public static const CAVE:int									= 19;
//public static const FOREST:int									= 20;
//public static const JUNGLE:int									= 21;
//public static const DESERT:int									= 22;
//public static const PLANE:int									= 23;
//public static const PLANT_BULB:int								= 24;

// This room is deprecated. It is only left to not screw saves inside it.
rooms["VR_POD_ROOM"] = new RoomClass(this);
rooms["VR_POD_ROOM"].roomName = "VR POD\nROOM";
rooms["VR_POD_ROOM"].description = "This small closet contains only virtual reality pod.";
rooms["VR_POD_ROOM"].planet = "";
rooms["VR_POD_ROOM"].system = "";
//rooms["VR_POD_ROOM"].eastExit = "SHIP INTERIOR";
rooms["VR_POD_ROOM"].addFlag(GLOBAL.INDOOR);
rooms["VR_POD_ROOM"].addFlag(GLOBAL.PRIVATE);
rooms["VR_POD_ROOM"].runOnEnter = cockyVrJunctionMenu;

rooms["GUILD EMBASSY"] = new RoomClass(this);
rooms["GUILD EMBASSY"].roomName = "STELLAR\nFURNACE";
rooms["GUILD EMBASSY"].planet = "TAVROS STATION";
rooms["GUILD EMBASSY"].system = "SYSTEM: KALAS";
rooms["GUILD EMBASSY"].northExit = "9006";
rooms["GUILD EMBASSY"].addFlag(GLOBAL.INDOOR);
rooms["GUILD EMBASSY"].addFlag(GLOBAL.PRIVATE);
rooms["GUILD EMBASSY"].addFlag(GLOBAL.NPC);
rooms["GUILD EMBASSY"].runOnEnter = guildEmbassyBonusFunction;

rooms["COC_CAMP"] = new RoomClass(this);
rooms["COC_CAMP"].roomName = "\nCAMPSITE";
rooms["COC_CAMP"].planet = "YOUR CAMP";
rooms["COC_CAMP"].system = "PLANET: MARETH";
rooms["COC_CAMP"].addFlag(GLOBAL.PRIVATE);
rooms["COC_CAMP"].addFlag(GLOBAL.BED);
rooms["COC_CAMP"].runOnEnter = cocCampMenu;

// SAND WITCHES CAVE

rooms["COC_DESERT_CAVE_ENTRACE"] = new RoomClass(this);
rooms["COC_DESERT_CAVE_ENTRACE"].moveMinutes = 1;
rooms["COC_DESERT_CAVE_ENTRACE"].roomName = "CAVE\nENTRACE";
rooms["COC_DESERT_CAVE_ENTRACE"].planet = "DESERT CAVE";
rooms["COC_DESERT_CAVE_ENTRACE"].system = "PLANET: MARETH";
rooms["COC_DESERT_CAVE_ENTRACE"].northExit = "COC_DESERT_CAVE_COMMONS";
rooms["COC_DESERT_CAVE_ENTRACE"].addFlag(GLOBAL.OUTDOOR);
rooms["COC_DESERT_CAVE_ENTRACE"].addFlag(GLOBAL.DESERT);
rooms["COC_DESERT_CAVE_ENTRACE"].addFlag(GLOBAL.PRIVATE);
rooms["COC_DESERT_CAVE_ENTRACE"].runOnEnter = DesertCaveEntrance;

rooms["COC_DESERT_CAVE_COMMONS"] = new RoomClass(this);
rooms["COC_DESERT_CAVE_COMMONS"].moveMinutes = 1;
rooms["COC_DESERT_CAVE_COMMONS"].roomName = "CAVERNOUS\nCOMMONS";
rooms["COC_DESERT_CAVE_COMMONS"].planet = "DESERT CAVE";
rooms["COC_DESERT_CAVE_COMMONS"].system = "PLANET: MARETH";
rooms["COC_DESERT_CAVE_COMMONS"].southExit = "COC_DESERT_CAVE_ENTRACE";
rooms["COC_DESERT_CAVE_COMMONS"].westExit = "COC_DESERT_CAVE_WEST_HALL_1";
rooms["COC_DESERT_CAVE_COMMONS"].eastExit = "COC_DESERT_CAVE_EAST_HALL_1";
rooms["COC_DESERT_CAVE_COMMONS"].northExit = "COC_DESERT_CAVE_ALTAR";
rooms["COC_DESERT_CAVE_COMMONS"].addFlag(GLOBAL.INDOOR);
rooms["COC_DESERT_CAVE_COMMONS"].addFlag(GLOBAL.HAZARD);
rooms["COC_DESERT_CAVE_COMMONS"].addFlag(GLOBAL.NOFAP);
rooms["COC_DESERT_CAVE_COMMONS"].addFlag(GLOBAL.CAVE);
rooms["COC_DESERT_CAVE_COMMONS"].addFlag(GLOBAL.PUBLIC);
rooms["COC_DESERT_CAVE_COMMONS"].runOnEnter = DesertCaveCommons;
//dungeons.setDungeonButtons(null, checkExit, roomWestHall1, roomEastHall1)

rooms["COC_DESERT_CAVE_WEST_HALL_1"] = new RoomClass(this);
rooms["COC_DESERT_CAVE_WEST_HALL_1"].description = "The supernatural illumination so prevalent to the east is present here as well, though in smaller quantity and vastly diminished brightness.  Swirls of bluish-white hue slide along the ceiling in slow, measured motions, a stark contrast to the jubilant dancing of the preceding cavern.  The ceiling is almost twelve feet high in places, with the sides of the east-west passage dipping down the lowest.  The floor is sandstone here, as you would expect in a desert cave, though it is liberally obfuscated with an array of woven rugs.  Sand Witches march by on errands, only pausing to give you disinterested glances.  Most of them bear the signs of pregnancy or have young girls in tow.  Whatever the case, there doesn't seem to be any fight in these women.  Along the north and south walls are small, door-sized openings, draped with heavy curtains that easily muffle any noise.  To the west, the tunnel bores on unimpeded.  However, to the east the cave opens up into a much, much larger chamber.";
rooms["COC_DESERT_CAVE_WEST_HALL_1"].moveMinutes = 1;
rooms["COC_DESERT_CAVE_WEST_HALL_1"].roomName = "WEST HALL";
rooms["COC_DESERT_CAVE_WEST_HALL_1"].planet = "DESERT CAVE";
rooms["COC_DESERT_CAVE_WEST_HALL_1"].system = "PLANET: MARETH";
rooms["COC_DESERT_CAVE_WEST_HALL_1"].eastExit = "COC_DESERT_CAVE_COMMONS";
rooms["COC_DESERT_CAVE_WEST_HALL_1"].westExit = "COC_DESERT_CAVE_WEST_HALL_2";
rooms["COC_DESERT_CAVE_WEST_HALL_1"].northExit = "COC_DESERT_CAVE_PLAY_ROOM";
rooms["COC_DESERT_CAVE_WEST_HALL_1"].southExit = "COC_DESERT_CAVE_LUST_ROOM";
rooms["COC_DESERT_CAVE_WEST_HALL_1"].addFlag(GLOBAL.INDOOR);
rooms["COC_DESERT_CAVE_WEST_HALL_1"].addFlag(GLOBAL.HAZARD);
rooms["COC_DESERT_CAVE_WEST_HALL_1"].addFlag(GLOBAL.NOFAP);
rooms["COC_DESERT_CAVE_WEST_HALL_1"].addFlag(GLOBAL.CAVE);
rooms["COC_DESERT_CAVE_WEST_HALL_1"].addFlag(GLOBAL.PUBLIC);

rooms["COC_DESERT_CAVE_PLAY_ROOM"] = new RoomClass(this);
rooms["COC_DESERT_CAVE_PLAY_ROOM"].description = "Behind the thick curtain is the last thing you would expect to see.  There's nearly a dozen children and three busty, pregnant sand witches watching them.  Toys have been scattered everywhere by the young blonde children.  Their wardens were busy knitting when you intruded, but they glare at you balefully and make shooing gestures.  Unless you had planned to rob children of their toys and beat up pregnant women, there's nothing to be had here.";
rooms["COC_DESERT_CAVE_PLAY_ROOM"].moveMinutes = 1;
rooms["COC_DESERT_CAVE_PLAY_ROOM"].roomName = "PLAY\nROOM";
rooms["COC_DESERT_CAVE_PLAY_ROOM"].planet = "DESERT CAVE";
rooms["COC_DESERT_CAVE_PLAY_ROOM"].system = "PLANET: MARETH";
rooms["COC_DESERT_CAVE_PLAY_ROOM"].southExit = "COC_DESERT_CAVE_WEST_HALL_1";
rooms["COC_DESERT_CAVE_PLAY_ROOM"].addFlag(GLOBAL.INDOOR);
rooms["COC_DESERT_CAVE_PLAY_ROOM"].addFlag(GLOBAL.HAZARD);
rooms["COC_DESERT_CAVE_PLAY_ROOM"].addFlag(GLOBAL.NOFAP);
rooms["COC_DESERT_CAVE_PLAY_ROOM"].addFlag(GLOBAL.CAVE);
rooms["COC_DESERT_CAVE_PLAY_ROOM"].addFlag(GLOBAL.PUBLIC);

rooms["COC_DESERT_CAVE_LUST_ROOM"] = new RoomClass(this);
rooms["COC_DESERT_CAVE_LUST_ROOM"].moveMinutes = 1;
rooms["COC_DESERT_CAVE_LUST_ROOM"].roomName = "LUST\nROOM";
rooms["COC_DESERT_CAVE_LUST_ROOM"].planet = "DESERT CAVE";
rooms["COC_DESERT_CAVE_LUST_ROOM"].system = "PLANET: MARETH";
rooms["COC_DESERT_CAVE_LUST_ROOM"].northExit = "COC_DESERT_CAVE_WEST_HALL_1";
rooms["COC_DESERT_CAVE_LUST_ROOM"].addFlag(GLOBAL.INDOOR);
rooms["COC_DESERT_CAVE_LUST_ROOM"].addFlag(GLOBAL.HAZARD);
rooms["COC_DESERT_CAVE_LUST_ROOM"].addFlag(GLOBAL.NOFAP);
rooms["COC_DESERT_CAVE_LUST_ROOM"].addFlag(GLOBAL.CAVE);
rooms["COC_DESERT_CAVE_LUST_ROOM"].addFlag(GLOBAL.NPC);
rooms["COC_DESERT_CAVE_LUST_ROOM"].addFlag(GLOBAL.PUBLIC);
rooms["COC_DESERT_CAVE_LUST_ROOM"].runOnEnter = DesertCaveLustRoom;

rooms["COC_DESERT_CAVE_WEST_HALL_2"] = new RoomClass(this);
rooms["COC_DESERT_CAVE_WEST_HALL_2"].moveMinutes = 1;
rooms["COC_DESERT_CAVE_WEST_HALL_2"].roomName = "WEST HALL";
rooms["COC_DESERT_CAVE_WEST_HALL_2"].planet = "DESERT CAVE";
rooms["COC_DESERT_CAVE_WEST_HALL_2"].system = "PLANET: MARETH";
rooms["COC_DESERT_CAVE_WEST_HALL_2"].eastExit = "COC_DESERT_CAVE_WEST_HALL_1";
rooms["COC_DESERT_CAVE_WEST_HALL_2"].southExit = "COC_DESERT_CAVE_PHARMACY";
rooms["COC_DESERT_CAVE_WEST_HALL_2"].northExit = "COC_DESERT_CAVE_NURSERY";
rooms["COC_DESERT_CAVE_WEST_HALL_2"].addFlag(GLOBAL.INDOOR);
rooms["COC_DESERT_CAVE_WEST_HALL_2"].addFlag(GLOBAL.HAZARD);
rooms["COC_DESERT_CAVE_WEST_HALL_2"].addFlag(GLOBAL.NOFAP);
rooms["COC_DESERT_CAVE_WEST_HALL_2"].addFlag(GLOBAL.CAVE);
rooms["COC_DESERT_CAVE_WEST_HALL_2"].addFlag(GLOBAL.PUBLIC);
rooms["COC_DESERT_CAVE_WEST_HALL_2"].runOnEnter = DesertCaveWestHall2;

rooms["COC_DESERT_CAVE_NURSERY"] = new RoomClass(this);
rooms["COC_DESERT_CAVE_NURSERY"].description = "As soon as you clear the curtain, you realize there's nothing of interest to you here.  The room is lit with rose pink globes, and the furniture in the room is filled with sleeping mothers, nursing infants, or older children taking naps.  The room is packed with bodies, and while it smells strongly of femininity, there's nothing worth looking into present here.";
rooms["COC_DESERT_CAVE_NURSERY"].moveMinutes = 1;
rooms["COC_DESERT_CAVE_NURSERY"].roomName = "NURSERY";
rooms["COC_DESERT_CAVE_NURSERY"].planet = "DESERT CAVE";
rooms["COC_DESERT_CAVE_NURSERY"].system = "PLANET: MARETH";
rooms["COC_DESERT_CAVE_NURSERY"].southExit = "COC_DESERT_CAVE_WEST_HALL_2";
rooms["COC_DESERT_CAVE_NURSERY"].addFlag(GLOBAL.INDOOR);
rooms["COC_DESERT_CAVE_NURSERY"].addFlag(GLOBAL.HAZARD);
rooms["COC_DESERT_CAVE_NURSERY"].addFlag(GLOBAL.NOFAP);
rooms["COC_DESERT_CAVE_NURSERY"].addFlag(GLOBAL.CAVE);
rooms["COC_DESERT_CAVE_NURSERY"].addFlag(GLOBAL.PUBLIC);

rooms["COC_DESERT_CAVE_PHARMACY"] = new RoomClass(this);
rooms["COC_DESERT_CAVE_PHARMACY"].moveMinutes = 1;
rooms["COC_DESERT_CAVE_PHARMACY"].roomName = "PHARMACY";
rooms["COC_DESERT_CAVE_PHARMACY"].planet = "DESERT CAVE";
rooms["COC_DESERT_CAVE_PHARMACY"].system = "PLANET: MARETH";
rooms["COC_DESERT_CAVE_PHARMACY"].northExit = "COC_DESERT_CAVE_WEST_HALL_2";
rooms["COC_DESERT_CAVE_PHARMACY"].addFlag(GLOBAL.INDOOR);
rooms["COC_DESERT_CAVE_PHARMACY"].addFlag(GLOBAL.HAZARD);
rooms["COC_DESERT_CAVE_PHARMACY"].addFlag(GLOBAL.NOFAP);
rooms["COC_DESERT_CAVE_PHARMACY"].addFlag(GLOBAL.CAVE);
rooms["COC_DESERT_CAVE_PHARMACY"].addFlag(GLOBAL.PRIVATE);
rooms["COC_DESERT_CAVE_PHARMACY"].runOnEnter = DesertCavePharmacy;

rooms["COC_DESERT_CAVE_EAST_HALL_1"] = new RoomClass(this);
rooms["COC_DESERT_CAVE_EAST_HALL_1"].description = "This smooth, sandstone tunnel proceeds in a perfectly straight line from east to west, as if aligned to some titanic, invisible compass buried below the floor.  Flickering white plumes of illumination undulate through the air along the arched ceiling, trailing streamers of pearl incandescence that light the entire chamber with ghostly brightness.  You are at the entrance to the eastern warrens - the commons are still clearly visible to the west, and the pathway to the east goes on a-ways.  Hand woven tapestries adorn the walls, telling the history of this enclave in pictographic form, from its inception to present day.  Further east, you can see a few empty places, ready to be covered with more cloth, once the next chapter of history is ready to be told.  To the north, there is a small opening in the wall, blocked off by plain white curtains.";
rooms["COC_DESERT_CAVE_EAST_HALL_1"].moveMinutes = 1;
rooms["COC_DESERT_CAVE_EAST_HALL_1"].roomName = "EAST HALL";
rooms["COC_DESERT_CAVE_EAST_HALL_1"].planet = "DESERT CAVE";
rooms["COC_DESERT_CAVE_EAST_HALL_1"].system = "PLANET: MARETH";
rooms["COC_DESERT_CAVE_EAST_HALL_1"].northExit = "COC_DESERT_CAVE_SLEEPING_CHAMBER";
rooms["COC_DESERT_CAVE_EAST_HALL_1"].westExit = "COC_DESERT_CAVE_COMMONS";
rooms["COC_DESERT_CAVE_EAST_HALL_1"].eastExit = "COC_DESERT_CAVE_EAST_HALL_2";
rooms["COC_DESERT_CAVE_EAST_HALL_1"].addFlag(GLOBAL.INDOOR);
rooms["COC_DESERT_CAVE_EAST_HALL_1"].addFlag(GLOBAL.HAZARD);
rooms["COC_DESERT_CAVE_EAST_HALL_1"].addFlag(GLOBAL.NOFAP);
rooms["COC_DESERT_CAVE_EAST_HALL_1"].addFlag(GLOBAL.CAVE);
rooms["COC_DESERT_CAVE_EAST_HALL_1"].addFlag(GLOBAL.PUBLIC);

rooms["COC_DESERT_CAVE_SLEEPING_CHAMBER"] = new RoomClass(this);
rooms["COC_DESERT_CAVE_SLEEPING_CHAMBER"].description = "Inside this expansive but cosy chamber are a few dozen beds, arranged in neat patterns marred only by a few cots that dare to be positioned adjacent to one another.  Clearly this is the tribe's primary sleeping area.  The floor is obscured by heavy, hand-woven rugs that ruffle oh so softly against your [pc.feet].  Instead of the usual ghostly lights you've grown to expect, the interior of this dwelling is lit by glass-paneled constructs resembling lanterns.  There is no fuel or wick of course, only flicking phantasmal illumination trapped as if it were a flame.  Shutters allow the lanterns to be dimmed, but as you are alone in here for now, there's no reason to make it harder to see.  There is a door to the east and a curtained off opening to the south.";
rooms["COC_DESERT_CAVE_SLEEPING_CHAMBER"].moveMinutes = 1;
rooms["COC_DESERT_CAVE_SLEEPING_CHAMBER"].roomName = "SLEEPING\nCHAMBER";
rooms["COC_DESERT_CAVE_SLEEPING_CHAMBER"].planet = "DESERT CAVE";
rooms["COC_DESERT_CAVE_SLEEPING_CHAMBER"].system = "PLANET: MARETH";
rooms["COC_DESERT_CAVE_SLEEPING_CHAMBER"].eastExit = "COC_DESERT_CAVE_BATHROOM";
rooms["COC_DESERT_CAVE_SLEEPING_CHAMBER"].southExit = "COC_DESERT_CAVE_EAST_HALL_1";
rooms["COC_DESERT_CAVE_SLEEPING_CHAMBER"].addFlag(GLOBAL.INDOOR);
rooms["COC_DESERT_CAVE_SLEEPING_CHAMBER"].addFlag(GLOBAL.HAZARD);
rooms["COC_DESERT_CAVE_SLEEPING_CHAMBER"].addFlag(GLOBAL.NOFAP);
rooms["COC_DESERT_CAVE_SLEEPING_CHAMBER"].addFlag(GLOBAL.CAVE);
rooms["COC_DESERT_CAVE_SLEEPING_CHAMBER"].addFlag(GLOBAL.PUBLIC);

rooms["COC_DESERT_CAVE_BATHROOM"] = new RoomClass(this);
rooms["COC_DESERT_CAVE_BATHROOM"].moveMinutes = 1;
rooms["COC_DESERT_CAVE_BATHROOM"].roomName = "BATHROOM";
rooms["COC_DESERT_CAVE_BATHROOM"].planet = "DESERT CAVE";
rooms["COC_DESERT_CAVE_BATHROOM"].system = "PLANET: MARETH";
rooms["COC_DESERT_CAVE_BATHROOM"].westExit = "COC_DESERT_CAVE_SLEEPING_CHAMBER";
rooms["COC_DESERT_CAVE_BATHROOM"].addFlag(GLOBAL.INDOOR);
rooms["COC_DESERT_CAVE_BATHROOM"].addFlag(GLOBAL.HAZARD);
rooms["COC_DESERT_CAVE_BATHROOM"].addFlag(GLOBAL.NOFAP);
rooms["COC_DESERT_CAVE_BATHROOM"].addFlag(GLOBAL.CAVE);
rooms["COC_DESERT_CAVE_BATHROOM"].addFlag(GLOBAL.PUBLIC);
rooms["COC_DESERT_CAVE_BATHROOM"].runOnEnter = DesertCaveBathroom;

rooms["COC_DESERT_CAVE_EAST_HALL_2"] = new RoomClass(this);
rooms["COC_DESERT_CAVE_EAST_HALL_2"].description = "Coming to an end here, the eastern warrens' main hall ends in little more than a bare, flat stone wall.  The area is well illuminated by the familiar magical lights, giving you a good view of the historical tapestries and blank spaces yet to be filled in.  You can't help but wonder if the Witches will simply stop recording their history once this area is full, or if they will expand in order to give themselves more room.  Looking over the events depicted here, it's clear that this enclave is one of the oldest, roughly two decades old.  There are pictures of a blond haired woman in fluttering, golden robes leaving a town of demons behind and journeying towards the desert.  Could that be how the sand witches began?  You shake your head and look over the rest of the room.  There's a curtained off doorway to the south, and of course, the tunnel leads back to the west.";
rooms["COC_DESERT_CAVE_EAST_HALL_2"].moveMinutes = 1;
rooms["COC_DESERT_CAVE_EAST_HALL_2"].roomName = "EAST HALL";
rooms["COC_DESERT_CAVE_EAST_HALL_2"].planet = "DESERT CAVE";
rooms["COC_DESERT_CAVE_EAST_HALL_2"].system = "PLANET: MARETH";
rooms["COC_DESERT_CAVE_EAST_HALL_2"].southExit = "COC_DESERT_CAVE_CUM_WITCH_BEDROOM";
rooms["COC_DESERT_CAVE_EAST_HALL_2"].westExit = "COC_DESERT_CAVE_EAST_HALL_1";
rooms["COC_DESERT_CAVE_EAST_HALL_2"].addFlag(GLOBAL.INDOOR);
rooms["COC_DESERT_CAVE_EAST_HALL_2"].addFlag(GLOBAL.HAZARD);
rooms["COC_DESERT_CAVE_EAST_HALL_2"].addFlag(GLOBAL.NOFAP);
rooms["COC_DESERT_CAVE_EAST_HALL_2"].addFlag(GLOBAL.CAVE);
rooms["COC_DESERT_CAVE_EAST_HALL_2"].addFlag(GLOBAL.PUBLIC);

rooms["COC_DESERT_CAVE_CUM_WITCH_BEDROOM"] = new RoomClass(this);
rooms["COC_DESERT_CAVE_CUM_WITCH_BEDROOM"].description = "As soon as you brush back the curtain, you're assaulted by a pungent, salty smell.  It almost reminds you of tepid ocean water... or cum.  Regardless, you force your way in and take a look around.  This area has all the furnishings of a small domicile and comes complete with a solid oak bed and mattress.  The mattress and sheets seem to be cared for with immaculate precision, perhaps magically aided.  There is a simple dresser here, and though it looks to have been fashioned by crude tools, the wood looks sturdy and serviceable.  All of the drawers are closed, of course.  A few books sit on a nearby table, but it's obvious they're written in a language beyond your comprehension.  Whoever wrote them either did so in a different tongue or a magical language that would take years to decipher.  A thick curtain walls this chamber off from the eastern warrens' main hall, to the north.  To the west, there is a thinner, gauzy sheet hanging from an opening in the rock - likely leading to a similar room.";
rooms["COC_DESERT_CAVE_CUM_WITCH_BEDROOM"].moveMinutes = 1;
rooms["COC_DESERT_CAVE_CUM_WITCH_BEDROOM"].roomName = "CUM WITCH\nBEDROOM";
rooms["COC_DESERT_CAVE_CUM_WITCH_BEDROOM"].planet = "DESERT CAVE";
rooms["COC_DESERT_CAVE_CUM_WITCH_BEDROOM"].system = "PLANET: MARETH";
rooms["COC_DESERT_CAVE_CUM_WITCH_BEDROOM"].northExit = "COC_DESERT_CAVE_EAST_HALL_2";
rooms["COC_DESERT_CAVE_CUM_WITCH_BEDROOM"].westExit = "COC_DESERT_CAVE_CUM_WITCH_OFFICE";
rooms["COC_DESERT_CAVE_CUM_WITCH_BEDROOM"].addFlag(GLOBAL.INDOOR);
rooms["COC_DESERT_CAVE_CUM_WITCH_BEDROOM"].addFlag(GLOBAL.HAZARD);
rooms["COC_DESERT_CAVE_CUM_WITCH_BEDROOM"].addFlag(GLOBAL.NOFAP);
rooms["COC_DESERT_CAVE_CUM_WITCH_BEDROOM"].addFlag(GLOBAL.CAVE);
rooms["COC_DESERT_CAVE_CUM_WITCH_BEDROOM"].addFlag(GLOBAL.PRIVATE);

rooms["COC_DESERT_CAVE_CUM_WITCH_OFFICE"] = new RoomClass(this);
rooms["COC_DESERT_CAVE_CUM_WITCH_OFFICE"].moveMinutes = 1;
rooms["COC_DESERT_CAVE_CUM_WITCH_OFFICE"].roomName = "CUM WITCH\nOFFICE";
rooms["COC_DESERT_CAVE_CUM_WITCH_OFFICE"].planet = "DESERT CAVE";
rooms["COC_DESERT_CAVE_CUM_WITCH_OFFICE"].system = "PLANET: MARETH";
rooms["COC_DESERT_CAVE_CUM_WITCH_OFFICE"].eastExit = "COC_DESERT_CAVE_CUM_WITCH_BEDROOM";
rooms["COC_DESERT_CAVE_CUM_WITCH_OFFICE"].addFlag(GLOBAL.INDOOR);
rooms["COC_DESERT_CAVE_CUM_WITCH_OFFICE"].addFlag(GLOBAL.HAZARD);
rooms["COC_DESERT_CAVE_CUM_WITCH_OFFICE"].addFlag(GLOBAL.NOFAP);
rooms["COC_DESERT_CAVE_CUM_WITCH_OFFICE"].addFlag(GLOBAL.CAVE);
rooms["COC_DESERT_CAVE_CUM_WITCH_OFFICE"].addFlag(GLOBAL.NPC);
rooms["COC_DESERT_CAVE_CUM_WITCH_OFFICE"].addFlag(GLOBAL.PRIVATE);
rooms["COC_DESERT_CAVE_CUM_WITCH_OFFICE"].runOnEnter = DesertCaveCumWitchOffice;

rooms["COC_DESERT_CAVE_ALTAR"] = new RoomClass(this);
rooms["COC_DESERT_CAVE_ALTAR"].description = "This chamber clearly holds some kind of important significance to the witch coven.  The floor and walls are covered in shining white, reflective tiles, and a large number of carved jugs ring the outer edge of the room.  The entire place smells faintly of milk.  Sniffing, you close in on the source of the aroma.  It's emanating from what looks like a golden well, positioned dead-center before you.  The various containers also smell faintly of the alabaster treat, and oddly, you can't catch even a single whiff of spoilage; it all smells fresh.  There must be some magic at work.  Peeping over the edge of the well, you can barely make out what seems like a sea of milk stored below: white-capped ivory waves sloshing around in a chamber so large you can't see the walls of it.  It must be preserved through magic.\n\nThere is a doorway to the south and one on the north wall.";
rooms["COC_DESERT_CAVE_ALTAR"].moveMinutes = 1;
rooms["COC_DESERT_CAVE_ALTAR"].roomName = "ALTAR";
rooms["COC_DESERT_CAVE_ALTAR"].planet = "DESERT CAVE";
rooms["COC_DESERT_CAVE_ALTAR"].system = "PLANET: MARETH";
rooms["COC_DESERT_CAVE_ALTAR"].northExit = "COC_DESERT_CAVE_THRONE";
rooms["COC_DESERT_CAVE_ALTAR"].southExit = "COC_DESERT_CAVE_COMMONS";
rooms["COC_DESERT_CAVE_ALTAR"].addFlag(GLOBAL.INDOOR);
rooms["COC_DESERT_CAVE_ALTAR"].addFlag(GLOBAL.HAZARD);
rooms["COC_DESERT_CAVE_ALTAR"].addFlag(GLOBAL.NOFAP);
rooms["COC_DESERT_CAVE_ALTAR"].addFlag(GLOBAL.CAVE);
rooms["COC_DESERT_CAVE_ALTAR"].addFlag(GLOBAL.PUBLIC);
rooms["COC_DESERT_CAVE_ALTAR"].runOnEnter = DesertCaveAltarRoom;

rooms["COC_DESERT_CAVE_THRONE"] = new RoomClass(this);
rooms["COC_DESERT_CAVE_THRONE"].moveMinutes = 1;
rooms["COC_DESERT_CAVE_THRONE"].roomName = "SAND MOTHER\nTHRONE";
rooms["COC_DESERT_CAVE_THRONE"].planet = "DESERT CAVE";
rooms["COC_DESERT_CAVE_THRONE"].system = "PLANET: MARETH";
rooms["COC_DESERT_CAVE_THRONE"].southExit = "COC_DESERT_CAVE_ALTAR";
rooms["COC_DESERT_CAVE_THRONE"].addFlag(GLOBAL.INDOOR);
rooms["COC_DESERT_CAVE_THRONE"].addFlag(GLOBAL.HAZARD);
rooms["COC_DESERT_CAVE_THRONE"].addFlag(GLOBAL.NOFAP);
rooms["COC_DESERT_CAVE_THRONE"].addFlag(GLOBAL.CAVE);
rooms["COC_DESERT_CAVE_THRONE"].addFlag(GLOBAL.NPC);
rooms["COC_DESERT_CAVE_THRONE"].addFlag(GLOBAL.PUBLIC);
rooms["COC_DESERT_CAVE_THRONE"].runOnEnter = DesertCaveSandMotherThrone;


// DEMONIC FACTORY

rooms["COC_FACTORY_FOYER"] = new RoomClass(this);
rooms["COC_FACTORY_FOYER"].moveMinutes = 1;
rooms["COC_FACTORY_FOYER"].roomName = "FACTORY\nENTRACE";
rooms["COC_FACTORY_FOYER"].planet = "DEMONIC FACTORY";
rooms["COC_FACTORY_FOYER"].system = "PLANET: MARETH";
rooms["COC_FACTORY_FOYER"].westExit = "COC_FACTORY_BATHROOM";
rooms["COC_FACTORY_FOYER"].eastExit = "COC_FACTORY_BREAK_ROOM";
rooms["COC_FACTORY_FOYER"].northExit = "COC_FACTORY_PUMP_ROOM";
rooms["COC_FACTORY_FOYER"].addFlag(GLOBAL.INDOOR);
rooms["COC_FACTORY_FOYER"].addFlag(GLOBAL.PRIVATE);
rooms["COC_FACTORY_FOYER"].addFlag(GLOBAL.HAZARD);
rooms["COC_FACTORY_FOYER"].addFlag(GLOBAL.NOFAP);
rooms["COC_FACTORY_FOYER"].runOnEnter = DemonFactoryFoyer;

rooms["COC_FACTORY_BREAK_ROOM"] = new RoomClass(this);
rooms["COC_FACTORY_BREAK_ROOM"].moveMinutes = 1;
rooms["COC_FACTORY_BREAK_ROOM"].roomName = "BREAK\nROOM";
rooms["COC_FACTORY_BREAK_ROOM"].planet = "DEMONIC FACTORY";
rooms["COC_FACTORY_BREAK_ROOM"].system = "PLANET: MARETH";
rooms["COC_FACTORY_BREAK_ROOM"].westExit = "COC_FACTORY_FOYER";
rooms["COC_FACTORY_BREAK_ROOM"].addFlag(GLOBAL.INDOOR);
rooms["COC_FACTORY_BREAK_ROOM"].addFlag(GLOBAL.PRIVATE);
rooms["COC_FACTORY_BREAK_ROOM"].addFlag(GLOBAL.HAZARD);
rooms["COC_FACTORY_BREAK_ROOM"].addFlag(GLOBAL.NOFAP);
rooms["COC_FACTORY_BREAK_ROOM"].runOnEnter = DemonFactoryBreakRoom;

rooms["COC_FACTORY_PUMP_ROOM"] = new RoomClass(this);
rooms["COC_FACTORY_PUMP_ROOM"].moveMinutes = 1;
rooms["COC_FACTORY_PUMP_ROOM"].roomName = "PUMP\nROOM";
rooms["COC_FACTORY_PUMP_ROOM"].planet = "DEMONIC FACTORY";
rooms["COC_FACTORY_PUMP_ROOM"].system = "PLANET: MARETH";
rooms["COC_FACTORY_PUMP_ROOM"].northExit = "COC_FACTORY_REPAIR_CLOSET";
rooms["COC_FACTORY_PUMP_ROOM"].southExit = "COC_FACTORY_FOYER";
rooms["COC_FACTORY_PUMP_ROOM"].westExit = "COC_FACTORY_MAIN_CHAMBER";
rooms["COC_FACTORY_PUMP_ROOM"].eastExit = "COC_FACTORY_FURNACE_ROOM";
rooms["COC_FACTORY_PUMP_ROOM"].addFlag(GLOBAL.INDOOR);
rooms["COC_FACTORY_PUMP_ROOM"].addFlag(GLOBAL.PRIVATE);
rooms["COC_FACTORY_PUMP_ROOM"].addFlag(GLOBAL.HAZARD);
rooms["COC_FACTORY_PUMP_ROOM"].addFlag(GLOBAL.NOFAP);
rooms["COC_FACTORY_PUMP_ROOM"].runOnEnter = DemonFactoryPumpRoom;

rooms["COC_FACTORY_FURNACE_ROOM"] = new RoomClass(this);
rooms["COC_FACTORY_FURNACE_ROOM"].moveMinutes = 1;
rooms["COC_FACTORY_FURNACE_ROOM"].roomName = "FURNACE\nROOM";
rooms["COC_FACTORY_FURNACE_ROOM"].planet = "DEMONIC FACTORY";
rooms["COC_FACTORY_FURNACE_ROOM"].system = "PLANET: MARETH";
rooms["COC_FACTORY_FURNACE_ROOM"].westExit = "COC_FACTORY_PUMP_ROOM";
rooms["COC_FACTORY_FURNACE_ROOM"].addFlag(GLOBAL.INDOOR);
rooms["COC_FACTORY_FURNACE_ROOM"].addFlag(GLOBAL.PRIVATE);
rooms["COC_FACTORY_FURNACE_ROOM"].addFlag(GLOBAL.HAZARD);
rooms["COC_FACTORY_FURNACE_ROOM"].addFlag(GLOBAL.NOFAP);
rooms["COC_FACTORY_FURNACE_ROOM"].runOnEnter = DemonFactoryFurnaceRoom;

rooms["COC_FACTORY_REPAIR_CLOSET"] = new RoomClass(this);
rooms["COC_FACTORY_REPAIR_CLOSET"].moveMinutes = 1;
rooms["COC_FACTORY_REPAIR_CLOSET"].roomName = "REPAIR\nCLOSET";
rooms["COC_FACTORY_REPAIR_CLOSET"].planet = "DEMONIC FACTORY";
rooms["COC_FACTORY_REPAIR_CLOSET"].system = "PLANET: MARETH";
rooms["COC_FACTORY_REPAIR_CLOSET"].southExit = "COC_FACTORY_PUMP_ROOM";
rooms["COC_FACTORY_REPAIR_CLOSET"].addFlag(GLOBAL.INDOOR);
rooms["COC_FACTORY_REPAIR_CLOSET"].addFlag(GLOBAL.PRIVATE);
rooms["COC_FACTORY_REPAIR_CLOSET"].addFlag(GLOBAL.HAZARD);
rooms["COC_FACTORY_REPAIR_CLOSET"].addFlag(GLOBAL.NOFAP);
rooms["COC_FACTORY_REPAIR_CLOSET"].runOnEnter = DemonFactoryRepairCloset;

rooms["COC_FACTORY_MAIN_CHAMBER"] = new RoomClass(this);
rooms["COC_FACTORY_MAIN_CHAMBER"].moveMinutes = 1;
rooms["COC_FACTORY_MAIN_CHAMBER"].roomName = "MAIN\nCHAMBER";
rooms["COC_FACTORY_MAIN_CHAMBER"].planet = "DEMONIC FACTORY";
rooms["COC_FACTORY_MAIN_CHAMBER"].system = "PLANET: MARETH";
rooms["COC_FACTORY_MAIN_CHAMBER"].eastExit = "COC_FACTORY_PUMP_ROOM";
rooms["COC_FACTORY_MAIN_CHAMBER"].inExit = "COC_FACTORY_FOREMAN_OFFICE";
rooms["COC_FACTORY_MAIN_CHAMBER"].inText = "Up";
rooms["COC_FACTORY_MAIN_CHAMBER"].addFlag(GLOBAL.INDOOR);
rooms["COC_FACTORY_MAIN_CHAMBER"].addFlag(GLOBAL.PUBLIC);
rooms["COC_FACTORY_MAIN_CHAMBER"].addFlag(GLOBAL.HAZARD);
rooms["COC_FACTORY_MAIN_CHAMBER"].addFlag(GLOBAL.NOFAP);
rooms["COC_FACTORY_MAIN_CHAMBER"].runOnEnter = DemonFactoryMainChamber;

rooms["COC_FACTORY_FOREMAN_OFFICE"] = new RoomClass(this);
rooms["COC_FACTORY_FOREMAN_OFFICE"].moveMinutes = 1;
rooms["COC_FACTORY_FOREMAN_OFFICE"].roomName = "FOREMAN\nOFFICE";
rooms["COC_FACTORY_FOREMAN_OFFICE"].planet = "DEMONIC FACTORY";
rooms["COC_FACTORY_FOREMAN_OFFICE"].system = "PLANET: MARETH";
rooms["COC_FACTORY_FOREMAN_OFFICE"].southExit = "COC_FACTORY_PREMIUM_PRODUCTS";
rooms["COC_FACTORY_FOREMAN_OFFICE"].eastExit = "COC_FACTORY_CONTROL_ROOM";
rooms["COC_FACTORY_FOREMAN_OFFICE"].outExit = "COC_FACTORY_MAIN_CHAMBER";
rooms["COC_FACTORY_FOREMAN_OFFICE"].outText = "Down";
rooms["COC_FACTORY_FOREMAN_OFFICE"].addFlag(GLOBAL.INDOOR);
rooms["COC_FACTORY_FOREMAN_OFFICE"].addFlag(GLOBAL.PRIVATE);
rooms["COC_FACTORY_FOREMAN_OFFICE"].addFlag(GLOBAL.HAZARD);
rooms["COC_FACTORY_FOREMAN_OFFICE"].addFlag(GLOBAL.NOFAP);
rooms["COC_FACTORY_FOREMAN_OFFICE"].runOnEnter = DemonFactoryForemanOffice;

rooms["COC_FACTORY_CONTROL_ROOM"] = new RoomClass(this);
rooms["COC_FACTORY_CONTROL_ROOM"].moveMinutes = 1;
rooms["COC_FACTORY_CONTROL_ROOM"].roomName = "CONTROL\nROOM";
rooms["COC_FACTORY_CONTROL_ROOM"].planet = "DEMONIC FACTORY";
rooms["COC_FACTORY_CONTROL_ROOM"].system = "PLANET: MARETH";
rooms["COC_FACTORY_CONTROL_ROOM"].westExit = "COC_FACTORY_FOREMAN_OFFICE";
rooms["COC_FACTORY_CONTROL_ROOM"].addFlag(GLOBAL.INDOOR);
rooms["COC_FACTORY_CONTROL_ROOM"].addFlag(GLOBAL.PRIVATE);
rooms["COC_FACTORY_CONTROL_ROOM"].addFlag(GLOBAL.HAZARD);
rooms["COC_FACTORY_CONTROL_ROOM"].addFlag(GLOBAL.NOFAP);
rooms["COC_FACTORY_CONTROL_ROOM"].runOnEnter = DemonFactoryControlRoom;

rooms["COC_FACTORY_PREMIUM_PRODUCTS"] = new RoomClass(this);
rooms["COC_FACTORY_PREMIUM_PRODUCTS"].moveMinutes = 1;
rooms["COC_FACTORY_PREMIUM_PRODUCTS"].roomName = "PREMIUM\nPRODUCTS";
rooms["COC_FACTORY_PREMIUM_PRODUCTS"].planet = "DEMONIC FACTORY";
rooms["COC_FACTORY_PREMIUM_PRODUCTS"].system = "PLANET: MARETH";
rooms["COC_FACTORY_PREMIUM_PRODUCTS"].northExit = "COC_FACTORY_FOREMAN_OFFICE";
rooms["COC_FACTORY_PREMIUM_PRODUCTS"].addFlag(GLOBAL.INDOOR);
rooms["COC_FACTORY_PREMIUM_PRODUCTS"].addFlag(GLOBAL.PRIVATE);
rooms["COC_FACTORY_PREMIUM_PRODUCTS"].addFlag(GLOBAL.HAZARD);
rooms["COC_FACTORY_PREMIUM_PRODUCTS"].addFlag(GLOBAL.NOFAP);
rooms["COC_FACTORY_PREMIUM_PRODUCTS"].runOnEnter = DemonFactoryPremiumStorage;

rooms["COC_FACTORY_BATHROOM"] = new RoomClass(this);
rooms["COC_FACTORY_BATHROOM"].moveMinutes = 1;
rooms["COC_FACTORY_BATHROOM"].roomName = "BATHROOM";
rooms["COC_FACTORY_BATHROOM"].planet = "DEMONIC FACTORY";
rooms["COC_FACTORY_BATHROOM"].system = "PLANET: MARETH";
rooms["COC_FACTORY_BATHROOM"].eastExit = "COC_FACTORY_FOYER";
rooms["COC_FACTORY_BATHROOM"].addFlag(GLOBAL.INDOOR);
rooms["COC_FACTORY_BATHROOM"].addFlag(GLOBAL.PRIVATE);
rooms["COC_FACTORY_BATHROOM"].addFlag(GLOBAL.HAZARD);
rooms["COC_FACTORY_BATHROOM"].runOnEnter = DemonFactoryBathroom;

// DEEP CAVE

rooms["COC_ZETAZ_ENTRACE"] = new RoomClass(this);
rooms["COC_ZETAZ_ENTRACE"].moveMinutes = 1;
rooms["COC_ZETAZ_ENTRACE"].roomName = "CAVE\nENTRACE";
rooms["COC_ZETAZ_ENTRACE"].planet = "DEEPWOODS CAVE";
rooms["COC_ZETAZ_ENTRACE"].system = "PLANET: MARETH";
rooms["COC_ZETAZ_ENTRACE"].northExit = "COC_ZETAZ_TUNNEL";
rooms["COC_ZETAZ_ENTRACE"].addFlag(GLOBAL.OUTDOOR);
rooms["COC_ZETAZ_ENTRACE"].addFlag(GLOBAL.JUNGLE);
rooms["COC_ZETAZ_ENTRACE"].runOnEnter = ZetazCaveEntrace;

rooms["COC_ZETAZ_TUNNEL"] = new RoomClass(this);
rooms["COC_ZETAZ_TUNNEL"].moveMinutes = 1;
rooms["COC_ZETAZ_TUNNEL"].roomName = "CAVE\nTUNNEL";
rooms["COC_ZETAZ_TUNNEL"].planet = "DEEPWOODS CAVE";
rooms["COC_ZETAZ_TUNNEL"].system = "PLANET: MARETH";
rooms["COC_ZETAZ_TUNNEL"].southExit = "COC_ZETAZ_ENTRACE";
rooms["COC_ZETAZ_TUNNEL"].northExit = "COC_ZETAZ_GATHERING_HALL";
rooms["COC_ZETAZ_TUNNEL"].addFlag(GLOBAL.INDOOR);
rooms["COC_ZETAZ_TUNNEL"].addFlag(GLOBAL.HAZARD);
rooms["COC_ZETAZ_TUNNEL"].addFlag(GLOBAL.NOFAP);
rooms["COC_ZETAZ_TUNNEL"].addFlag(GLOBAL.CAVE);
rooms["COC_ZETAZ_TUNNEL"].runOnEnter = ZetazCaveTunnel;

rooms["COC_ZETAZ_GATHERING_HALL"] = new RoomClass(this);
rooms["COC_ZETAZ_GATHERING_HALL"].moveMinutes = 1;
rooms["COC_ZETAZ_GATHERING_HALL"].roomName = "GATHERING\nHALL";
rooms["COC_ZETAZ_GATHERING_HALL"].planet = "DEEPWOODS CAVE";
rooms["COC_ZETAZ_GATHERING_HALL"].system = "PLANET: MARETH";
rooms["COC_ZETAZ_GATHERING_HALL"].southExit = "COC_ZETAZ_TUNNEL";
rooms["COC_ZETAZ_GATHERING_HALL"].westExit = "COC_ZETAZ_FUNGUS_CAVERN";
rooms["COC_ZETAZ_GATHERING_HALL"].eastExit = "COC_ZETAZ_TORTURE_ROOM";
rooms["COC_ZETAZ_GATHERING_HALL"].northExit = "COC_ZETAZ_CHAMBER";
rooms["COC_ZETAZ_GATHERING_HALL"].addFlag(GLOBAL.INDOOR);
rooms["COC_ZETAZ_GATHERING_HALL"].addFlag(GLOBAL.HAZARD);
rooms["COC_ZETAZ_GATHERING_HALL"].addFlag(GLOBAL.NOFAP);
rooms["COC_ZETAZ_GATHERING_HALL"].addFlag(GLOBAL.CAVE);
rooms["COC_ZETAZ_GATHERING_HALL"].runOnEnter = ZetazCaveGatheringHall;

rooms["COC_ZETAZ_FUNGUS_CAVERN"] = new RoomClass(this);
rooms["COC_ZETAZ_FUNGUS_CAVERN"].moveMinutes = 1;
rooms["COC_ZETAZ_FUNGUS_CAVERN"].roomName = "FUNGUS\nCAVERN";
rooms["COC_ZETAZ_FUNGUS_CAVERN"].planet = "DEEPWOODS CAVE";
rooms["COC_ZETAZ_FUNGUS_CAVERN"].system = "PLANET: MARETH";
rooms["COC_ZETAZ_FUNGUS_CAVERN"].eastExit = "COC_ZETAZ_GATHERING_HALL";
rooms["COC_ZETAZ_FUNGUS_CAVERN"].addFlag(GLOBAL.INDOOR);
rooms["COC_ZETAZ_FUNGUS_CAVERN"].addFlag(GLOBAL.HAZARD);
rooms["COC_ZETAZ_FUNGUS_CAVERN"].addFlag(GLOBAL.NOFAP);
rooms["COC_ZETAZ_FUNGUS_CAVERN"].addFlag(GLOBAL.CAVE);
rooms["COC_ZETAZ_FUNGUS_CAVERN"].runOnEnter = ZetazCaveFungusCavern;

rooms["COC_ZETAZ_TORTURE_ROOM"] = new RoomClass(this);
rooms["COC_ZETAZ_TORTURE_ROOM"].moveMinutes = 1;
rooms["COC_ZETAZ_TORTURE_ROOM"].roomName = "TORTURE\nROOM";
rooms["COC_ZETAZ_TORTURE_ROOM"].planet = "DEEPWOODS CAVE";
rooms["COC_ZETAZ_TORTURE_ROOM"].system = "PLANET: MARETH";
rooms["COC_ZETAZ_TORTURE_ROOM"].westExit = "COC_ZETAZ_GATHERING_HALL";
rooms["COC_ZETAZ_TORTURE_ROOM"].northExit = "COC_ZETAZ_SECRET_PASSAGE";
rooms["COC_ZETAZ_TORTURE_ROOM"].addFlag(GLOBAL.INDOOR);
rooms["COC_ZETAZ_TORTURE_ROOM"].addFlag(GLOBAL.HAZARD);
rooms["COC_ZETAZ_TORTURE_ROOM"].addFlag(GLOBAL.NOFAP);
rooms["COC_ZETAZ_TORTURE_ROOM"].addFlag(GLOBAL.CAVE);
rooms["COC_ZETAZ_TORTURE_ROOM"].runOnEnter = ZetazCaveTortureRoom;

rooms["COC_ZETAZ_SECRET_PASSAGE"] = new RoomClass(this);
rooms["COC_ZETAZ_SECRET_PASSAGE"].moveMinutes = 1;
rooms["COC_ZETAZ_SECRET_PASSAGE"].roomName = "SECRET\nPASSAGE";
rooms["COC_ZETAZ_SECRET_PASSAGE"].planet = "DEEPWOODS CAVE";
rooms["COC_ZETAZ_SECRET_PASSAGE"].system = "PLANET: MARETH";
rooms["COC_ZETAZ_SECRET_PASSAGE"].westExit = "COC_ZETAZ_CHAMBER";
rooms["COC_ZETAZ_SECRET_PASSAGE"].southExit = "COC_ZETAZ_TORTURE_ROOM";
rooms["COC_ZETAZ_SECRET_PASSAGE"].addFlag(GLOBAL.INDOOR);
rooms["COC_ZETAZ_SECRET_PASSAGE"].addFlag(GLOBAL.HAZARD);
rooms["COC_ZETAZ_SECRET_PASSAGE"].addFlag(GLOBAL.NOFAP);
rooms["COC_ZETAZ_SECRET_PASSAGE"].addFlag(GLOBAL.CAVE);
rooms["COC_ZETAZ_SECRET_PASSAGE"].runOnEnter = ZetazCaveSecretPassage;

rooms["COC_ZETAZ_CHAMBER"] = new RoomClass(this);
rooms["COC_ZETAZ_CHAMBER"].moveMinutes = 1;
rooms["COC_ZETAZ_CHAMBER"].roomName = "ZETAZ\nCHAMBER";
rooms["COC_ZETAZ_CHAMBER"].planet = "DEEPWOODS CAVE";
rooms["COC_ZETAZ_CHAMBER"].system = "PLANET: MARETH";
rooms["COC_ZETAZ_CHAMBER"].eastExit = "COC_ZETAZ_SECRET_PASSAGE";
rooms["COC_ZETAZ_CHAMBER"].southExit = "COC_ZETAZ_GATHERING_HALL";
rooms["COC_ZETAZ_CHAMBER"].addFlag(GLOBAL.INDOOR);
rooms["COC_ZETAZ_CHAMBER"].addFlag(GLOBAL.HAZARD);
rooms["COC_ZETAZ_CHAMBER"].addFlag(GLOBAL.NOFAP);
rooms["COC_ZETAZ_CHAMBER"].addFlag(GLOBAL.CAVE);
rooms["COC_ZETAZ_CHAMBER"].runOnEnter = ZetazCaveZetazChamber;

// LETHICE FORTRESS

rooms["COC FORTRESS ENTRACE"] = new RoomClass(this);
rooms["COC FORTRESS ENTRACE"].description = "The inside of this cave is damp and dark, but it bears signs of frequent use. The map you got from Zetaz matches the curves of this winding passage exactly. There can be no doubt that this is the place, even though his map ends a short distance into the tunnel. Either he knew it would be a linear path or was so familiar with the territory that he didn’t think it was worth writing down. You can go east, deeper into the mountain towards Lethice’s fortress, or leave to the west.";
rooms["COC FORTRESS ENTRACE"].moveMinutes = 3;
rooms["COC FORTRESS ENTRACE"].roomName = "FORTRESS\nENTRACE";
rooms["COC FORTRESS ENTRACE"].planet = "LETHICE FORTRESS";
rooms["COC FORTRESS ENTRACE"].system = "PLANET: MARETH";
rooms["COC FORTRESS ENTRACE"].eastExit = "COC FORTRESS TUNNEL 1";
rooms["COC FORTRESS ENTRACE"].addFlag(GLOBAL.INDOOR);
rooms["COC FORTRESS ENTRACE"].addFlag(GLOBAL.CAVE);
rooms["COC FORTRESS ENTRACE"].runOnEnter = LethiceFortressEntranceRoomFunc;

rooms["COC FORTRESS TUNNEL 1"] = new RoomClass(this);
rooms["COC FORTRESS TUNNEL 1"].description = "Winding back and forth, the tunnel gradually arcs west and north from here, sloping steeply upward in the latter direction. The upward sloping side must lead to Lethice’s fortress, supposedly at the top of the mountain. You’ll have to be careful down here. You doubt that such an entrance would be completely unguarded. As a matter of fact... you think you can see signs of worked stone to the north. You’re getting close to something.";
rooms["COC FORTRESS TUNNEL 1"].moveMinutes = 3;
rooms["COC FORTRESS TUNNEL 1"].roomName = "\nTUNNEL";
rooms["COC FORTRESS TUNNEL 1"].planet = "LETHICE FORTRESS";
rooms["COC FORTRESS TUNNEL 1"].system = "PLANET: MARETH";
rooms["COC FORTRESS TUNNEL 1"].westExit = "COC FORTRESS ENTRACE";
rooms["COC FORTRESS TUNNEL 1"].northExit = "COC FORTRESS ANTECHAMBER";
rooms["COC FORTRESS TUNNEL 1"].addFlag(GLOBAL.INDOOR);
rooms["COC FORTRESS TUNNEL 1"].addFlag(GLOBAL.CAVE);
rooms["COC FORTRESS TUNNEL 1"].addFlag(GLOBAL.HAZARD);

rooms["COC FORTRESS ANTECHAMBER"] = new RoomClass(this);
rooms["COC FORTRESS ANTECHAMBER"].description = "You are standing in a large, gloomy lobby, lit by the drear yellow pulse of gas lamps. The walls, floor and distant ceiling are uniformly built from a dark, aged stone which serves to make the vault-like space shadowy and oppressive, despite its size. The floor has been polished a dull bronze by years of use and the distant sound of activity permeates the air; it has the atmosphere of a place which is thronged with people during rush hour but is for now as deserted as a school corridor during class hours. Something to be grateful for perhaps, but you should get a move on.\n\nAhead is a large archway. Through it you can see some sort of dark screen set into a wall. On the right is a much smaller metal door, which looks like it might be a storage room.";
rooms["COC FORTRESS ANTECHAMBER"].moveMinutes = 3;
rooms["COC FORTRESS ANTECHAMBER"].roomName = "\nANTECHAMBER";
rooms["COC FORTRESS ANTECHAMBER"].planet = "LETHICE FORTRESS";
rooms["COC FORTRESS ANTECHAMBER"].system = "PLANET: MARETH";
rooms["COC FORTRESS ANTECHAMBER"].northExit = "COC FORTRESS MAGPIE HALL S";
rooms["COC FORTRESS ANTECHAMBER"].eastExit = "COC FORTRESS MIRRORS";
rooms["COC FORTRESS ANTECHAMBER"].southExit = "COC FORTRESS TUNNEL 1";
rooms["COC FORTRESS ANTECHAMBER"].addFlag(GLOBAL.INDOOR);
rooms["COC FORTRESS ANTECHAMBER"].addFlag(GLOBAL.HAZARD);

rooms["COC FORTRESS MIRRORS"] = new RoomClass(this);
rooms["COC FORTRESS MIRRORS"].moveMinutes = 3;
rooms["COC FORTRESS MIRRORS"].roomName = "MIRRORS\nROOM";
rooms["COC FORTRESS MIRRORS"].planet = "LETHICE FORTRESS";
rooms["COC FORTRESS MIRRORS"].system = "PLANET: MARETH";
rooms["COC FORTRESS MIRRORS"].westExit = "COC FORTRESS ANTECHAMBER";
rooms["COC FORTRESS MIRRORS"].addFlag(GLOBAL.INDOOR);
rooms["COC FORTRESS MIRRORS"].addFlag(GLOBAL.HAZARD);
rooms["COC FORTRESS MIRRORS"].runOnEnter = LethiceFortressMirrorsRoomFunc;

rooms["COC FORTRESS MAGPIE HALL S"] = new RoomClass(this);
rooms["COC FORTRESS MAGPIE HALL S"].moveMinutes = 3;
rooms["COC FORTRESS MAGPIE HALL S"].roomName = "MAGPIE\nHALL SOUTH";
rooms["COC FORTRESS MAGPIE HALL S"].planet = "LETHICE FORTRESS";
rooms["COC FORTRESS MAGPIE HALL S"].system = "PLANET: MARETH";
rooms["COC FORTRESS MAGPIE HALL S"].northExit = "COC FORTRESS MAGPIE HALL N";
rooms["COC FORTRESS MAGPIE HALL S"].southExit = "COC FORTRESS ANTECHAMBER";
rooms["COC FORTRESS MAGPIE HALL S"].addFlag(GLOBAL.INDOOR);
rooms["COC FORTRESS MAGPIE HALL S"].addFlag(GLOBAL.HAZARD);
rooms["COC FORTRESS MAGPIE HALL S"].runOnEnter = LethiceFortressMagpieHallSRoomFunc;

rooms["COC FORTRESS MAGPIE HALL N"] = new RoomClass(this);
rooms["COC FORTRESS MAGPIE HALL N"].moveMinutes = 3;
rooms["COC FORTRESS MAGPIE HALL N"].roomName = "MAGPIE\nHALL NORTH";
rooms["COC FORTRESS MAGPIE HALL N"].planet = "LETHICE FORTRESS";
rooms["COC FORTRESS MAGPIE HALL N"].system = "PLANET: MARETH";
rooms["COC FORTRESS MAGPIE HALL N"].northExit = "COC FORTRESS TUNNEL 2";
rooms["COC FORTRESS MAGPIE HALL N"].southExit = "COC FORTRESS MAGPIE HALL S";
rooms["COC FORTRESS MAGPIE HALL N"].addFlag(GLOBAL.INDOOR);
rooms["COC FORTRESS MAGPIE HALL N"].addFlag(GLOBAL.HAZARD);
rooms["COC FORTRESS MAGPIE HALL N"].runOnEnter = LethiceFortressMagpieHallNRoomFunc;

rooms["COC FORTRESS TUNNEL 2"] = new RoomClass(this);
rooms["COC FORTRESS TUNNEL 2"].description = "Light trickles in from the east. After all the trekking through these subterranean holes, you’ve got to be close to the mountain’s summit. You know that down the steeply sloped passage will take you back through the basilisks’ chamber if you want to leave the way you came, but a second trip through that crowded hall might be ill-advised. It’d be best to move forward into the sun.";
rooms["COC FORTRESS TUNNEL 2"].moveMinutes = 3;
rooms["COC FORTRESS TUNNEL 2"].roomName = "\nTUNNEL";
rooms["COC FORTRESS TUNNEL 2"].planet = "LETHICE FORTRESS";
rooms["COC FORTRESS TUNNEL 2"].system = "PLANET: MARETH";
rooms["COC FORTRESS TUNNEL 2"].northExit = "COC FORTRESS EDGE";
rooms["COC FORTRESS TUNNEL 2"].southExit = "COC FORTRESS MAGPIE HALL N";
rooms["COC FORTRESS TUNNEL 2"].addFlag(GLOBAL.INDOOR);
rooms["COC FORTRESS TUNNEL 2"].addFlag(GLOBAL.HAZARD);

rooms["COC FORTRESS EDGE"] = new RoomClass(this);
rooms["COC FORTRESS EDGE"].description = "Standing on the edge of the mountain's summit, you can see Mareth for miles in all direction. It's fairly disconcerting to focus on long with the constant shifting and twisting of the wasted areas, but here and there you can pick out islands of stability in the ephemeral terrain. You blink your eyes to clear the nauseating landscape from your view and turn back to the way ahead. Lethice's fortress lies a short distance to the north, its walls tall and stout. The gates themselves hang open. Likely she didn't expect anyone to make it this far.";
rooms["COC FORTRESS EDGE"].moveMinutes = 3;
rooms["COC FORTRESS EDGE"].roomName = "FORTRESS\nEDGE";
rooms["COC FORTRESS EDGE"].planet = "LETHICE FORTRESS";
rooms["COC FORTRESS EDGE"].system = "PLANET: MARETH";
rooms["COC FORTRESS EDGE"].northExit = "COC FORTRESS NORTH ENTRY";
rooms["COC FORTRESS EDGE"].southExit = "COC FORTRESS TUNNEL 2";
rooms["COC FORTRESS EDGE"].addFlag(GLOBAL.INDOOR);
rooms["COC FORTRESS EDGE"].addFlag(GLOBAL.HAZARD);

rooms["COC FORTRESS NORTH ENTRY"] = new RoomClass(this);
rooms["COC FORTRESS NORTH ENTRY"].description = "You now stand in the archway that is the southern entrance to Lethice's headquarters. The place is built like a castle. You can't see too much from your shaded position, but the bricks that surround you are individual as big as horses. The gates themselves are crafted of wood that looks at least a century old, reinforced with bands of gleaming metal that you doubt will ever rust. A barren cliffside can be seen to the south, the demon queen's lair to the north.";
rooms["COC FORTRESS NORTH ENTRY"].moveMinutes = 3;
rooms["COC FORTRESS NORTH ENTRY"].roomName = "NORTH\nENTRY";
rooms["COC FORTRESS NORTH ENTRY"].planet = "LETHICE FORTRESS";
rooms["COC FORTRESS NORTH ENTRY"].system = "PLANET: MARETH";
rooms["COC FORTRESS NORTH ENTRY"].northExit = "COC FORTRESS SOUTH COURTYARD";
rooms["COC FORTRESS NORTH ENTRY"].southExit = "COC FORTRESS EDGE";
rooms["COC FORTRESS NORTH ENTRY"].addFlag(GLOBAL.INDOOR);
rooms["COC FORTRESS NORTH ENTRY"].addFlag(GLOBAL.HAZARD);

rooms["COC FORTRESS SOUTH COURTYARD"] = new RoomClass(this);
rooms["COC FORTRESS SOUTH COURTYARD"].description = "Lethice's courtyard is surprisingly well-groomed for a place that's supposedly home to neverending debauchery and depravity. The paths are laid with interconnecting sandstone bricks that reflect the sun to give the place a gentle, amber glow, and lush, green grass lines the sides along with well-trimmed hedges. You could almost mistake this place for a churchyard if it wasn't for the faint sound of moans on the wind. The courtyard paths lead away east and west, while the gateway out hangs open to the south.";
rooms["COC FORTRESS SOUTH COURTYARD"].moveMinutes = 3;
rooms["COC FORTRESS SOUTH COURTYARD"].roomName = "SOUTH\nCOURTYARD";
rooms["COC FORTRESS SOUTH COURTYARD"].planet = "LETHICE FORTRESS";
rooms["COC FORTRESS SOUTH COURTYARD"].system = "PLANET: MARETH";
rooms["COC FORTRESS SOUTH COURTYARD"].eastExit = "COC FORTRESS SOUTHEAST COURTYARD";
rooms["COC FORTRESS SOUTH COURTYARD"].westExit = "COC FORTRESS SOUTHWEST COURTYARD";
rooms["COC FORTRESS SOUTH COURTYARD"].southExit = "COC FORTRESS NORTH ENTRY";
rooms["COC FORTRESS SOUTH COURTYARD"].addFlag(GLOBAL.INDOOR);
rooms["COC FORTRESS SOUTH COURTYARD"].addFlag(GLOBAL.HAZARD);

rooms["COC FORTRESS SOUTHWEST COURTYARD"] = new RoomClass(this);
rooms["COC FORTRESS SOUTHWEST COURTYARD"].description = "Some of the nearby bushes are blooming, filling the air with their sweet scent, unlike any flowers you’ve encounter before. Their petals are a multitude of colors, and their scents, though laced with corruption, are as sweet and pleasant as anything you've had the pleasure of smelling. The path you're treading upon curves north and east from here along the thick, red walls. Vines seem to crowd the way to the north. There are no signs of any ramps or ladders to get to the battlements, but there is a doorway to the west marked as 'Forge Wing'. A notice declares it closed for repairs.";
rooms["COC FORTRESS SOUTHWEST COURTYARD"].moveMinutes = 3;
rooms["COC FORTRESS SOUTHWEST COURTYARD"].roomName = "SOUTHWEST\nCOURTYARD";
rooms["COC FORTRESS SOUTHWEST COURTYARD"].planet = "LETHICE FORTRESS";
rooms["COC FORTRESS SOUTHWEST COURTYARD"].system = "PLANET: MARETH";
rooms["COC FORTRESS SOUTHWEST COURTYARD"].eastExit = "COC FORTRESS SOUTH COURTYARD";
rooms["COC FORTRESS SOUTHWEST COURTYARD"].northExit = "COC FORTRESS SOUTHWEST WALK";
rooms["COC FORTRESS SOUTHWEST COURTYARD"].addFlag(GLOBAL.INDOOR);
rooms["COC FORTRESS SOUTHWEST COURTYARD"].addFlag(GLOBAL.HAZARD);

rooms["COC FORTRESS SOUTHWEST WALK"] = new RoomClass(this);
rooms["COC FORTRESS SOUTHWEST WALK"].moveMinutes = 3;
rooms["COC FORTRESS SOUTHWEST WALK"].roomName = "SOUTHWEST\nWALK";
rooms["COC FORTRESS SOUTHWEST WALK"].planet = "LETHICE FORTRESS";
rooms["COC FORTRESS SOUTHWEST WALK"].system = "PLANET: MARETH";
rooms["COC FORTRESS SOUTHWEST WALK"].northExit = "COC FORTRESS WEST WALK";
rooms["COC FORTRESS SOUTHWEST WALK"].southExit = "COC FORTRESS SOUTHWEST COURTYARD";
rooms["COC FORTRESS SOUTHWEST WALK"].addFlag(GLOBAL.INDOOR);
rooms["COC FORTRESS SOUTHWEST WALK"].addFlag(GLOBAL.HAZARD);
rooms["COC FORTRESS SOUTHWEST WALK"].runOnEnter = LethiceFortressSouthWestWalkRoomFunc;

rooms["COC FORTRESS WEST WALK"] = new RoomClass(this);
rooms["COC FORTRESS WEST WALK"].moveMinutes = 3;
rooms["COC FORTRESS WEST WALK"].roomName = "WEST\nWALK";
rooms["COC FORTRESS WEST WALK"].planet = "LETHICE FORTRESS";
rooms["COC FORTRESS WEST WALK"].system = "PLANET: MARETH";
rooms["COC FORTRESS WEST WALK"].northExit = "COC FORTRESS NORTHWEST WALK";
rooms["COC FORTRESS WEST WALK"].southExit = "COC FORTRESS SOUTHWEST WALK";
rooms["COC FORTRESS WEST WALK"].eastExit = "COC FORTRESS COURTYARD SQUARE";
rooms["COC FORTRESS WEST WALK"].addFlag(GLOBAL.INDOOR);
rooms["COC FORTRESS WEST WALK"].addFlag(GLOBAL.HAZARD);
rooms["COC FORTRESS WEST WALK"].runOnEnter = LethiceFortressWestWalkRoomFunc;

rooms["COC FORTRESS NORTHWEST WALK"] = new RoomClass(this);
rooms["COC FORTRESS NORTHWEST WALK"].description = "A narrow path splits from the sandstone thoroughfare towards a pair of double doors to the west. The craftsmanship of the carpenter who made them is on full display; intricate designs of dragons engaged in sexual positions of all kinds are carved around the outer edges of the frame while more mundane, eye-pleasing patterns decorate the center panels. Above, a sign designates this area as the library. Unfortunately the doors are sealed closed. Perhaps the library is not yet written. You smirk at your own joke.\n\nThe courtyard itself continues much as it has elsewhere. The bushes to the south appear more unruly than elsewhere, but to the north there appears to be nothing but pleasant walking through this botanical paradise.";
rooms["COC FORTRESS NORTHWEST WALK"].moveMinutes = 3;
rooms["COC FORTRESS NORTHWEST WALK"].roomName = "NORTHWEST\nWALK";
rooms["COC FORTRESS NORTHWEST WALK"].planet = "LETHICE FORTRESS";
rooms["COC FORTRESS NORTHWEST WALK"].system = "PLANET: MARETH";
rooms["COC FORTRESS NORTHWEST WALK"].northExit = "COC FORTRESS NORTHWEST COURTYARD";
rooms["COC FORTRESS NORTHWEST WALK"].southExit = "COC FORTRESS WEST WALK";
rooms["COC FORTRESS NORTHWEST WALK"].addFlag(GLOBAL.INDOOR);
rooms["COC FORTRESS NORTHWEST WALK"].addFlag(GLOBAL.HAZARD);

rooms["COC FORTRESS NORTHWEST COURTYARD"] = new RoomClass(this);
rooms["COC FORTRESS NORTHWEST COURTYARD"].description = "The courtyard comes to an abrupt end here, hemmed in by a impressively high stone wall to the north, high enough to shame the walls in the other cardinal directions. The path is also bounded in by stonework to the west, forcing it to curve to the east and south around a bush that has been tastelessly shaped to resemble a turgid prick. The demons even went so far as to trim ivory flowers into a contiguous path along one side, very much looking like a stream of arboreal spunk.";
rooms["COC FORTRESS NORTHWEST COURTYARD"].moveMinutes = 3;
rooms["COC FORTRESS NORTHWEST COURTYARD"].roomName = "NORTHWEST\nCOURTYARD";
rooms["COC FORTRESS NORTHWEST COURTYARD"].planet = "LETHICE FORTRESS";
rooms["COC FORTRESS NORTHWEST COURTYARD"].system = "PLANET: MARETH";
rooms["COC FORTRESS NORTHWEST COURTYARD"].eastExit = "COC FORTRESS NORTH COURTYARD";
rooms["COC FORTRESS NORTHWEST COURTYARD"].southExit = "COC FORTRESS NORTHWEST WALK";
rooms["COC FORTRESS NORTHWEST COURTYARD"].addFlag(GLOBAL.INDOOR);
rooms["COC FORTRESS NORTHWEST COURTYARD"].addFlag(GLOBAL.HAZARD);

rooms["COC FORTRESS NORTH COURTYARD"] = new RoomClass(this);
rooms["COC FORTRESS NORTH COURTYARD"].moveMinutes = 3;
rooms["COC FORTRESS NORTH COURTYARD"].roomName = "NORTH\nCOURTYARD";
rooms["COC FORTRESS NORTH COURTYARD"].planet = "LETHICE FORTRESS";
rooms["COC FORTRESS NORTH COURTYARD"].system = "PLANET: MARETH";
rooms["COC FORTRESS NORTH COURTYARD"].eastExit = "COC FORTRESS NORTHEAST COURTYARD";
rooms["COC FORTRESS NORTH COURTYARD"].westExit = "COC FORTRESS NORTHWEST COURTYARD";
rooms["COC FORTRESS NORTH COURTYARD"].northExit = "COC FORTRESS THRONE ROOM";
rooms["COC FORTRESS NORTH COURTYARD"].addFlag(GLOBAL.INDOOR);
rooms["COC FORTRESS NORTH COURTYARD"].addFlag(GLOBAL.HAZARD);
rooms["COC FORTRESS NORTH COURTYARD"].runOnEnter = LethiceFortressNorthCourtyardRoomFunc;

rooms["COC FORTRESS NORTHEAST COURTYARD"] = new RoomClass(this);
rooms["COC FORTRESS NORTHEAST COURTYARD"].moveMinutes = 3;
rooms["COC FORTRESS NORTHEAST COURTYARD"].roomName = "NORTHEAST\nCOURTYARD";
rooms["COC FORTRESS NORTHEAST COURTYARD"].planet = "LETHICE FORTRESS";
rooms["COC FORTRESS NORTHEAST COURTYARD"].system = "PLANET: MARETH";
rooms["COC FORTRESS NORTHEAST COURTYARD"].westExit = "COC FORTRESS NORTH COURTYARD";
rooms["COC FORTRESS NORTHEAST COURTYARD"].southExit = "COC FORTRESS NORTHEAST WALK";
rooms["COC FORTRESS NORTHEAST COURTYARD"].addFlag(GLOBAL.INDOOR);
rooms["COC FORTRESS NORTHEAST COURTYARD"].addFlag(GLOBAL.HAZARD);
rooms["COC FORTRESS NORTHEAST COURTYARD"].runOnEnter = LethiceFortressNorthEastCourtyardRoomFunc;

rooms["COC FORTRESS NORTHEAST WALK"] = new RoomClass(this);
rooms["COC FORTRESS NORTHEAST WALK"].description = "The air is pleasant and free here. Not even the corrupt nature of this place can stop you from enjoying this moment in the demon queen’s garden. Still, there is an aura of lingering danger here. The flowers smell pleasant but somehow off, and every now and again the breezes carry the sounds of whorish moans. An entryway in the east wall leads towards the barracks and mess, identified by a simple sign to the left of the imposing iron door frame. Fortunately, the door is barred and sealed. It seems you’ve come at a time when Lethice’s fortress is near empy. How fortunate for you.";
rooms["COC FORTRESS NORTHEAST WALK"].moveMinutes = 3;
rooms["COC FORTRESS NORTHEAST WALK"].roomName = "NORTHEAST\nWALK";
rooms["COC FORTRESS NORTHEAST WALK"].planet = "LETHICE FORTRESS";
rooms["COC FORTRESS NORTHEAST WALK"].system = "PLANET: MARETH";
rooms["COC FORTRESS NORTHEAST WALK"].northExit = "COC FORTRESS NORTHEAST COURTYARD";
rooms["COC FORTRESS NORTHEAST WALK"].southExit = "COC FORTRESS EAST WALK";
rooms["COC FORTRESS NORTHEAST WALK"].addFlag(GLOBAL.INDOOR);
rooms["COC FORTRESS NORTHEAST WALK"].addFlag(GLOBAL.HAZARD);

rooms["COC FORTRESS EAST WALK"] = new RoomClass(this);
rooms["COC FORTRESS EAST WALK"].moveMinutes = 3;
rooms["COC FORTRESS EAST WALK"].roomName = "EAST\nWALK";
rooms["COC FORTRESS EAST WALK"].planet = "LETHICE FORTRESS";
rooms["COC FORTRESS EAST WALK"].system = "PLANET: MARETH";
rooms["COC FORTRESS EAST WALK"].northExit = "COC FORTRESS NORTHEAST WALK";
rooms["COC FORTRESS EAST WALK"].southExit = "COC FORTRESS SOUTHEAST WALK";
rooms["COC FORTRESS EAST WALK"].westExit = "COC FORTRESS COURTYARD SQUARE";
rooms["COC FORTRESS EAST WALK"].addFlag(GLOBAL.INDOOR);
rooms["COC FORTRESS EAST WALK"].addFlag(GLOBAL.HAZARD);
rooms["COC FORTRESS EAST WALK"].runOnEnter = LethiceFortressEastWalkRoomFunc;

rooms["COC FORTRESS SOUTHEAST WALK"] = new RoomClass(this);
rooms["COC FORTRESS SOUTHEAST WALK"].description = "Swarms of butterflies congregate on the flowering bushes here. At first, the sight seems beautiful, almost pristine. Then, you spot the endemic corruption that Lethice has spread through the lands. They aren’t just swarms of butterflies - they’re swarms of mating butterflies, crawling all over each other in a swarm of sweet-smelling pollen and fluttering wings. You had best move on. The path leads north and south.";
rooms["COC FORTRESS SOUTHEAST WALK"].moveMinutes = 3;
rooms["COC FORTRESS SOUTHEAST WALK"].roomName = "SOUTHEAST\nWALK";
rooms["COC FORTRESS SOUTHEAST WALK"].planet = "LETHICE FORTRESS";
rooms["COC FORTRESS SOUTHEAST WALK"].system = "PLANET: MARETH";
rooms["COC FORTRESS SOUTHEAST WALK"].northExit = "COC FORTRESS EAST WALK";
rooms["COC FORTRESS SOUTHEAST WALK"].southExit = "COC FORTRESS SOUTHEAST COURTYARD";
rooms["COC FORTRESS SOUTHEAST WALK"].addFlag(GLOBAL.INDOOR);
rooms["COC FORTRESS SOUTHEAST WALK"].addFlag(GLOBAL.HAZARD);

rooms["COC FORTRESS SOUTHEAST COURTYARD"] = new RoomClass(this);
rooms["COC FORTRESS SOUTHEAST COURTYARD"].description = "Walking along the sandstone path, you're treated to a remarkably peaceful view. Up here, above the clouds the ring the mountain, it's almost too easy to let your guard down. A small hole in the southern wall of Lethice's fortress appears to the south. Peeking through, you can see machinery and some kind of lift suspended over the cliffside. That must be how the demons can come and go safely. You can continue to walk among the bushes to the north and west. An iron door to the east bears lettering denoting it as 'recreation'. A small placard explains that it's currently off limits due to renovations. Graffiti below complains about some contractor named Fenoxo delivering on his promised work schedule.";
rooms["COC FORTRESS SOUTHEAST COURTYARD"].moveMinutes = 3;
rooms["COC FORTRESS SOUTHEAST COURTYARD"].roomName = "SOUTHEAST\nCOURTYARD";
rooms["COC FORTRESS SOUTHEAST COURTYARD"].planet = "LETHICE FORTRESS";
rooms["COC FORTRESS SOUTHEAST COURTYARD"].system = "PLANET: MARETH";
rooms["COC FORTRESS SOUTHEAST COURTYARD"].northExit = "COC FORTRESS SOUTHEAST WALK";
rooms["COC FORTRESS SOUTHEAST COURTYARD"].westExit = "COC FORTRESS SOUTH COURTYARD";
rooms["COC FORTRESS SOUTHEAST COURTYARD"].southExit = "COC FORTRESS GREAT LIFT";
rooms["COC FORTRESS SOUTHEAST COURTYARD"].addFlag(GLOBAL.INDOOR);
rooms["COC FORTRESS SOUTHEAST COURTYARD"].addFlag(GLOBAL.HAZARD);

rooms["COC FORTRESS COURTYARD SQUARE"] = new RoomClass(this);
rooms["COC FORTRESS COURTYARD SQUARE"].moveMinutes = 3;
rooms["COC FORTRESS COURTYARD SQUARE"].roomName = "COURTYARD\nSQUARE";
rooms["COC FORTRESS COURTYARD SQUARE"].planet = "LETHICE FORTRESS";
rooms["COC FORTRESS COURTYARD SQUARE"].system = "PLANET: MARETH";
rooms["COC FORTRESS COURTYARD SQUARE"].eastExit = "COC FORTRESS EAST WALK";
rooms["COC FORTRESS COURTYARD SQUARE"].westExit = "COC FORTRESS WEST WALK";
rooms["COC FORTRESS COURTYARD SQUARE"].addFlag(GLOBAL.INDOOR);
rooms["COC FORTRESS COURTYARD SQUARE"].addFlag(GLOBAL.HAZARD);
rooms["COC FORTRESS COURTYARD SQUARE"].runOnEnter = LethiceFortressCourtyardSquareRoomFunc;

rooms["COC FORTRESS GREAT LIFT"] = new RoomClass(this);
rooms["COC FORTRESS GREAT LIFT"].moveMinutes = 3;
rooms["COC FORTRESS GREAT LIFT"].roomName = "GREAT\nLIFT";
rooms["COC FORTRESS GREAT LIFT"].planet = "LETHICE FORTRESS";
rooms["COC FORTRESS GREAT LIFT"].system = "PLANET: MARETH";
rooms["COC FORTRESS GREAT LIFT"].northExit = "COC FORTRESS SOUTHEAST COURTYARD";
rooms["COC FORTRESS GREAT LIFT"].addFlag(GLOBAL.INDOOR);
rooms["COC FORTRESS GREAT LIFT"].addFlag(GLOBAL.HAZARD);
rooms["COC FORTRESS GREAT LIFT"].runOnEnter = LethiceFortressGreatLiftRoomFunc;

rooms["COC FORTRESS THRONE ROOM"] = new RoomClass(this);
rooms["COC FORTRESS THRONE ROOM"].moveMinutes = 3;
rooms["COC FORTRESS THRONE ROOM"].roomName = "THRONE\nROOM";
rooms["COC FORTRESS THRONE ROOM"].planet = "LETHICE FORTRESS";
rooms["COC FORTRESS THRONE ROOM"].system = "PLANET: MARETH";
rooms["COC FORTRESS THRONE ROOM"].southExit = "COC FORTRESS NORTH COURTYARD";
rooms["COC FORTRESS THRONE ROOM"].addFlag(GLOBAL.INDOOR);
rooms["COC FORTRESS THRONE ROOM"].addFlag(GLOBAL.HAZARD);
rooms["COC FORTRESS THRONE ROOM"].runOnEnter = LethiceFortressThroneRoomFunc;