import classes.RoomClass;
import classes.GLOBAL;

//public static const INDOOR:int                                 = 0;
//public static const OUTDOOR:int                                = 1;
//public static const BED:int                                    = 2;
//public static const COMMERCE:int							   = 3;
//public static const BAR:int									   = 4;
//public static const NPC:int									   = 5;
//public static const MEDICAL:int								   = 6;
//public static const SHIPHANGAR:int							   = 7;
//public static const QUEST:int								   = 8;
//public static const OBJECTIVE:int						       = 9;
//public static const HAZARD:int								   = 10;
//public static const NOFAP:int 								   = 11;
//public static const LIFTUP:int 								   = 12;
//public static const LIFTDOWN:int 								= 13;
//public static const TAXI:int    								= 14;
//public static const PUBLIC:int 									= 15;
//public static const PRIVATE:int									= 16;
//public static const FAPPING_ILLEGAL:int							= 17;
//public static const NUDITY_ILLEGAL:int							= 18;
//public static const CAVE:int									= 19;
//public static const FOREST:int									= 20;
//public static const JUNGLE:int									= 21;
//public static const DESERT:int									= 22;
//public static const PLANE:int									= 23;
//public static const PLANT_BULB:int								= 24;

rooms["VR_POD_ROOM"] = new RoomClass(this);
rooms["VR_POD_ROOM"].roomName = "VR POD\nROOM";
rooms["VR_POD_ROOM"].description = "This small closet contains only virtual reality pod.";
rooms["VR_POD_ROOM"].planet = "";
rooms["VR_POD_ROOM"].system = "";
//rooms["VR_POD_ROOM"].eastExit = "SHIP INTERIOR";
rooms["VR_POD_ROOM"].addFlag(GLOBAL.INDOOR);
rooms["VR_POD_ROOM"].addFlag(GLOBAL.PRIVATE);
rooms["VR_POD_ROOM"].runOnEnter = cockyVrJunctionMenu;

rooms["COC_CAMP"] = new RoomClass(this);
rooms["COC_CAMP"].roomName = "\nCAMPSITE";
rooms["COC_CAMP"].planet = "YOUR CAMP";
rooms["COC_CAMP"].system = "PLANET: MARETH";
rooms["COC_CAMP"].addFlag(GLOBAL.PRIVATE);
rooms["COC_CAMP"].addFlag(GLOBAL.BED);
rooms["COC_CAMP"].runOnEnter = cocCampMenu;

// SAND WITCHES CAVE

rooms["COC_DESERT_CAVE_ENTRACE"] = new RoomClass(this);
rooms["COC_DESERT_CAVE_ENTRACE"].moveMinutes = 1;
rooms["COC_DESERT_CAVE_ENTRACE"].roomName = "CAVE\nENTRACE";
rooms["COC_DESERT_CAVE_ENTRACE"].planet = "DESERT CAVE";
rooms["COC_DESERT_CAVE_ENTRACE"].system = "PLANET: MARETH";
rooms["COC_DESERT_CAVE_ENTRACE"].northExit = "COC_DESERT_CAVE_COMMONS";
rooms["COC_DESERT_CAVE_ENTRACE"].addFlag(GLOBAL.OUTDOOR);
rooms["COC_DESERT_CAVE_ENTRACE"].addFlag(GLOBAL.DESERT);
rooms["COC_DESERT_CAVE_ENTRACE"].runOnEnter = DesertCaveEntrance;

rooms["COC_DESERT_CAVE_COMMONS"] = new RoomClass(this);
rooms["COC_DESERT_CAVE_COMMONS"].moveMinutes = 1;
rooms["COC_DESERT_CAVE_COMMONS"].roomName = "CAVERNOUS\nCOMMONS";
rooms["COC_DESERT_CAVE_COMMONS"].planet = "DESERT CAVE";
rooms["COC_DESERT_CAVE_COMMONS"].system = "PLANET: MARETH";
rooms["COC_DESERT_CAVE_COMMONS"].southExit = "COC_DESERT_CAVE_ENTRACE";
rooms["COC_DESERT_CAVE_COMMONS"].westExit = "COC_DESERT_CAVE_WEST_HALL_1";
rooms["COC_DESERT_CAVE_COMMONS"].eastExit = "COC_DESERT_CAVE_EAST_HALL_1";
rooms["COC_DESERT_CAVE_COMMONS"].northExit = "COC_DESERT_CAVE_ALTAR";
rooms["COC_DESERT_CAVE_COMMONS"].addFlag(GLOBAL.INDOOR);
rooms["COC_DESERT_CAVE_COMMONS"].addFlag(GLOBAL.HAZARD);
rooms["COC_DESERT_CAVE_COMMONS"].addFlag(GLOBAL.NOFAP);
rooms["COC_DESERT_CAVE_COMMONS"].addFlag(GLOBAL.CAVE);
rooms["COC_DESERT_CAVE_COMMONS"].runOnEnter = DesertCaveCommons;
//dungeons.setDungeonButtons(null, checkExit, roomWestHall1, roomEastHall1)

rooms["COC_DESERT_CAVE_WEST_HALL_1"] = new RoomClass(this);
rooms["COC_DESERT_CAVE_WEST_HALL_1"].description = "The supernatural illumination so prevalent to the east is present here as well, though in smaller quantity and vastly diminished brightness.  Swirls of bluish-white hue slide along the ceiling in slow, measured motions, a stark contrast to the jubilant dancing of the preceding cavern.  The ceiling is almost twelve feet high in places, with the sides of the east-west passage dipping down the lowest.  The floor is sandstone here, as you would expect in a desert cave, though it is liberally obfuscated with an array of woven rugs.  Sand Witches march by on errands, only pausing to give you disinterested glances.  Most of them bear the signs of pregnancy or have young girls in tow.  Whatever the case, there doesn't seem to be any fight in these women.  Along the north and south walls are small, door-sized openings, draped with heavy curtains that easily muffle any noise.  To the west, the tunnel bores on unimpeded.  However, to the east the cave opens up into a much, much larger chamber.";
rooms["COC_DESERT_CAVE_WEST_HALL_1"].moveMinutes = 1;
rooms["COC_DESERT_CAVE_WEST_HALL_1"].roomName = "WEST HALL";
rooms["COC_DESERT_CAVE_WEST_HALL_1"].planet = "DESERT CAVE";
rooms["COC_DESERT_CAVE_WEST_HALL_1"].system = "PLANET: MARETH";
rooms["COC_DESERT_CAVE_WEST_HALL_1"].eastExit = "COC_DESERT_CAVE_COMMONS";
rooms["COC_DESERT_CAVE_WEST_HALL_1"].westExit = "COC_DESERT_CAVE_WEST_HALL_2";
rooms["COC_DESERT_CAVE_WEST_HALL_1"].northExit = "COC_DESERT_CAVE_PLAY_ROOM";
rooms["COC_DESERT_CAVE_WEST_HALL_1"].southExit = "COC_DESERT_CAVE_LUST_ROOM";
rooms["COC_DESERT_CAVE_WEST_HALL_1"].addFlag(GLOBAL.INDOOR);
rooms["COC_DESERT_CAVE_WEST_HALL_1"].addFlag(GLOBAL.HAZARD);
rooms["COC_DESERT_CAVE_WEST_HALL_1"].addFlag(GLOBAL.NOFAP);
rooms["COC_DESERT_CAVE_WEST_HALL_1"].addFlag(GLOBAL.CAVE);

rooms["COC_DESERT_CAVE_PLAY_ROOM"] = new RoomClass(this);
rooms["COC_DESERT_CAVE_PLAY_ROOM"].description = "Behind the thick curtain is the last thing you would expect to see.  There's nearly a dozen children and three busty, pregnant sand witches watching them.  Toys have been scattered everywhere by the young blonde children.  Their wardens were busy knitting when you intruded, but they glare at you balefully and make shooing gestures.  Unless you had planned to rob children of their toys and beat up pregnant women, there's nothing to be had here.";
rooms["COC_DESERT_CAVE_PLAY_ROOM"].moveMinutes = 1;
rooms["COC_DESERT_CAVE_PLAY_ROOM"].roomName = "PLAY\nROOM";
rooms["COC_DESERT_CAVE_PLAY_ROOM"].planet = "DESERT CAVE";
rooms["COC_DESERT_CAVE_PLAY_ROOM"].system = "PLANET: MARETH";
rooms["COC_DESERT_CAVE_PLAY_ROOM"].southExit = "COC_DESERT_CAVE_WEST_HALL_1";
rooms["COC_DESERT_CAVE_PLAY_ROOM"].addFlag(GLOBAL.INDOOR);
rooms["COC_DESERT_CAVE_PLAY_ROOM"].addFlag(GLOBAL.HAZARD);
rooms["COC_DESERT_CAVE_PLAY_ROOM"].addFlag(GLOBAL.NOFAP);
rooms["COC_DESERT_CAVE_PLAY_ROOM"].addFlag(GLOBAL.CAVE);

rooms["COC_DESERT_CAVE_LUST_ROOM"] = new RoomClass(this);
rooms["COC_DESERT_CAVE_LUST_ROOM"].moveMinutes = 1;
rooms["COC_DESERT_CAVE_LUST_ROOM"].roomName = "LUST\nROOM";
rooms["COC_DESERT_CAVE_LUST_ROOM"].planet = "DESERT CAVE";
rooms["COC_DESERT_CAVE_LUST_ROOM"].system = "PLANET: MARETH";
rooms["COC_DESERT_CAVE_LUST_ROOM"].northExit = "COC_DESERT_CAVE_WEST_HALL_1";
rooms["COC_DESERT_CAVE_LUST_ROOM"].addFlag(GLOBAL.INDOOR);
rooms["COC_DESERT_CAVE_LUST_ROOM"].addFlag(GLOBAL.HAZARD);
rooms["COC_DESERT_CAVE_LUST_ROOM"].addFlag(GLOBAL.NOFAP);
rooms["COC_DESERT_CAVE_LUST_ROOM"].addFlag(GLOBAL.CAVE);
rooms["COC_DESERT_CAVE_LUST_ROOM"].runOnEnter = DesertCaveLustRoom;

rooms["COC_DESERT_CAVE_WEST_HALL_2"] = new RoomClass(this);
rooms["COC_DESERT_CAVE_WEST_HALL_2"].moveMinutes = 1;
rooms["COC_DESERT_CAVE_WEST_HALL_2"].roomName = "WEST HALL";
rooms["COC_DESERT_CAVE_WEST_HALL_2"].planet = "DESERT CAVE";
rooms["COC_DESERT_CAVE_WEST_HALL_2"].system = "PLANET: MARETH";
rooms["COC_DESERT_CAVE_WEST_HALL_2"].eastExit = "COC_DESERT_CAVE_WEST_HALL_1";
rooms["COC_DESERT_CAVE_WEST_HALL_2"].southExit = "COC_DESERT_CAVE_PHARMACY";
rooms["COC_DESERT_CAVE_WEST_HALL_2"].northExit = "COC_DESERT_CAVE_NURSERY";
rooms["COC_DESERT_CAVE_WEST_HALL_2"].addFlag(GLOBAL.INDOOR);
rooms["COC_DESERT_CAVE_WEST_HALL_2"].addFlag(GLOBAL.HAZARD);
rooms["COC_DESERT_CAVE_WEST_HALL_2"].addFlag(GLOBAL.NOFAP);
rooms["COC_DESERT_CAVE_WEST_HALL_2"].addFlag(GLOBAL.CAVE);
rooms["COC_DESERT_CAVE_WEST_HALL_2"].runOnEnter = DesertCaveWestHall2;

rooms["COC_DESERT_CAVE_NURSERY"] = new RoomClass(this);
rooms["COC_DESERT_CAVE_NURSERY"].description = "As soon as you clear the curtain, you realize there's nothing of interest to you here.  The room is lit with rose pink globes, and the furniture in the room is filled with sleeping mothers, nursing infants, or older children taking naps.  The room is packed with bodies, and while it smells strongly of femininity, there's nothing worth looking into present here.";
rooms["COC_DESERT_CAVE_NURSERY"].moveMinutes = 1;
rooms["COC_DESERT_CAVE_NURSERY"].roomName = "NURSERY";
rooms["COC_DESERT_CAVE_NURSERY"].planet = "DESERT CAVE";
rooms["COC_DESERT_CAVE_NURSERY"].system = "PLANET: MARETH";
rooms["COC_DESERT_CAVE_NURSERY"].southExit = "COC_DESERT_CAVE_WEST_HALL_2";
rooms["COC_DESERT_CAVE_NURSERY"].addFlag(GLOBAL.INDOOR);
rooms["COC_DESERT_CAVE_NURSERY"].addFlag(GLOBAL.HAZARD);
rooms["COC_DESERT_CAVE_NURSERY"].addFlag(GLOBAL.NOFAP);
rooms["COC_DESERT_CAVE_NURSERY"].addFlag(GLOBAL.CAVE);

rooms["COC_DESERT_CAVE_PHARMACY"] = new RoomClass(this);
rooms["COC_DESERT_CAVE_PHARMACY"].moveMinutes = 1;
rooms["COC_DESERT_CAVE_PHARMACY"].roomName = "PHARMACY";
rooms["COC_DESERT_CAVE_PHARMACY"].planet = "DESERT CAVE";
rooms["COC_DESERT_CAVE_PHARMACY"].system = "PLANET: MARETH";
rooms["COC_DESERT_CAVE_PHARMACY"].northExit = "COC_DESERT_CAVE_WEST_HALL_2";
rooms["COC_DESERT_CAVE_PHARMACY"].addFlag(GLOBAL.INDOOR);
rooms["COC_DESERT_CAVE_PHARMACY"].addFlag(GLOBAL.HAZARD);
rooms["COC_DESERT_CAVE_PHARMACY"].addFlag(GLOBAL.NOFAP);
rooms["COC_DESERT_CAVE_PHARMACY"].addFlag(GLOBAL.CAVE);
rooms["COC_DESERT_CAVE_PHARMACY"].runOnEnter = DesertCavePharmacy;

rooms["COC_DESERT_CAVE_EAST_HALL_1"] = new RoomClass(this);
rooms["COC_DESERT_CAVE_EAST_HALL_1"].description = "This smooth, sandstone tunnel proceeds in a perfectly straight line from east to west, as if aligned to some titanic, invisible compass buried below the floor.  Flickering white plumes of illumination undulate through the air along the arched ceiling, trailing streamers of pearl incandescence that light the entire chamber with ghostly brightness.  You are at the entrance to the eastern warrens - the commons are still clearly visible to the west, and the pathway to the east goes on a-ways.  Hand woven tapestries adorn the walls, telling the history of this enclave in pictographic form, from its inception to present day.  Further east, you can see a few empty places, ready to be covered with more cloth, once the next chapter of history is ready to be told.  To the north, there is a small opening in the wall, blocked off by plain white curtains.";
rooms["COC_DESERT_CAVE_EAST_HALL_1"].moveMinutes = 1;
rooms["COC_DESERT_CAVE_EAST_HALL_1"].roomName = "EAST HALL";
rooms["COC_DESERT_CAVE_EAST_HALL_1"].planet = "DESERT CAVE";
rooms["COC_DESERT_CAVE_EAST_HALL_1"].system = "PLANET: MARETH";
rooms["COC_DESERT_CAVE_EAST_HALL_1"].northExit = "COC_DESERT_CAVE_SLEEPING_CHAMBER";
rooms["COC_DESERT_CAVE_EAST_HALL_1"].westExit = "COC_DESERT_CAVE_COMMONS";
rooms["COC_DESERT_CAVE_EAST_HALL_1"].eastExit = "COC_DESERT_CAVE_EAST_HALL_2";
rooms["COC_DESERT_CAVE_EAST_HALL_1"].addFlag(GLOBAL.INDOOR);
rooms["COC_DESERT_CAVE_EAST_HALL_1"].addFlag(GLOBAL.HAZARD);
rooms["COC_DESERT_CAVE_EAST_HALL_1"].addFlag(GLOBAL.NOFAP);
rooms["COC_DESERT_CAVE_EAST_HALL_1"].addFlag(GLOBAL.CAVE);

rooms["COC_DESERT_CAVE_SLEEPING_CHAMBER"] = new RoomClass(this);
rooms["COC_DESERT_CAVE_SLEEPING_CHAMBER"].description = "Inside this expansive but cosy chamber are a few dozen beds, arranged in neat patterns marred only by a few cots that dare to be positioned adjacent to one another.  Clearly this is the tribe's primary sleeping area.  The floor is obscured by heavy, hand-woven rugs that ruffle oh so softly against your [pc.feet].  Instead of the usual ghostly lights you've grown to expect, the interior of this dwelling is lit by glass-paneled constructs resembling lanterns.  There is no fuel or wick of course, only flicking phantasmal illumination trapped as if it were a flame.  Shutters allow the lanterns to be dimmed, but as you are alone in here for now, there's no reason to make it harder to see.  There is a door to the east and a curtained off opening to the south.";
rooms["COC_DESERT_CAVE_SLEEPING_CHAMBER"].moveMinutes = 1;
rooms["COC_DESERT_CAVE_SLEEPING_CHAMBER"].roomName = "SLEEPING\nCHAMBER";
rooms["COC_DESERT_CAVE_SLEEPING_CHAMBER"].planet = "DESERT CAVE";
rooms["COC_DESERT_CAVE_SLEEPING_CHAMBER"].system = "PLANET: MARETH";
rooms["COC_DESERT_CAVE_SLEEPING_CHAMBER"].eastExit = "COC_DESERT_CAVE_BATHROOM";
rooms["COC_DESERT_CAVE_SLEEPING_CHAMBER"].southExit = "COC_DESERT_CAVE_EAST_HALL_1";
rooms["COC_DESERT_CAVE_SLEEPING_CHAMBER"].addFlag(GLOBAL.INDOOR);
rooms["COC_DESERT_CAVE_SLEEPING_CHAMBER"].addFlag(GLOBAL.HAZARD);
rooms["COC_DESERT_CAVE_SLEEPING_CHAMBER"].addFlag(GLOBAL.NOFAP);
rooms["COC_DESERT_CAVE_SLEEPING_CHAMBER"].addFlag(GLOBAL.CAVE);

rooms["COC_DESERT_CAVE_BATHROOM"] = new RoomClass(this);
rooms["COC_DESERT_CAVE_BATHROOM"].moveMinutes = 1;
rooms["COC_DESERT_CAVE_BATHROOM"].roomName = "BATHROOM";
rooms["COC_DESERT_CAVE_BATHROOM"].planet = "DESERT CAVE";
rooms["COC_DESERT_CAVE_BATHROOM"].system = "PLANET: MARETH";
rooms["COC_DESERT_CAVE_BATHROOM"].westExit = "COC_DESERT_CAVE_SLEEPING_CHAMBER";
rooms["COC_DESERT_CAVE_BATHROOM"].addFlag(GLOBAL.INDOOR);
rooms["COC_DESERT_CAVE_BATHROOM"].addFlag(GLOBAL.HAZARD);
rooms["COC_DESERT_CAVE_BATHROOM"].addFlag(GLOBAL.NOFAP);
rooms["COC_DESERT_CAVE_BATHROOM"].addFlag(GLOBAL.CAVE);
rooms["COC_DESERT_CAVE_BATHROOM"].runOnEnter = DesertCaveBathroom;

rooms["COC_DESERT_CAVE_EAST_HALL_2"] = new RoomClass(this);
rooms["COC_DESERT_CAVE_EAST_HALL_2"].description = "Coming to an end here, the eastern warrens' main hall ends in little more than a bare, flat stone wall.  The area is well illuminated by the familiar magical lights, giving you a good view of the historical tapestries and blank spaces yet to be filled in.  You can't help but wonder if the Witches will simply stop recording their history once this area is full, or if they will expand in order to give themselves more room.  Looking over the events depicted here, it's clear that this enclave is one of the oldest, roughly two decades old.  There are pictures of a blond haired woman in fluttering, golden robes leaving a town of demons behind and journeying towards the desert.  Could that be how the sand witches began?  You shake your head and look over the rest of the room.  There's a curtained off doorway to the south, and of course, the tunnel leads back to the west.";
rooms["COC_DESERT_CAVE_EAST_HALL_2"].moveMinutes = 1;
rooms["COC_DESERT_CAVE_EAST_HALL_2"].roomName = "EAST HALL";
rooms["COC_DESERT_CAVE_EAST_HALL_2"].planet = "DESERT CAVE";
rooms["COC_DESERT_CAVE_EAST_HALL_2"].system = "PLANET: MARETH";
rooms["COC_DESERT_CAVE_EAST_HALL_2"].southExit = "COC_DESERT_CAVE_CUM_WITCH_BEDROOM";
rooms["COC_DESERT_CAVE_EAST_HALL_2"].westExit = "COC_DESERT_CAVE_EAST_HALL_1";
rooms["COC_DESERT_CAVE_EAST_HALL_2"].addFlag(GLOBAL.INDOOR);
rooms["COC_DESERT_CAVE_EAST_HALL_2"].addFlag(GLOBAL.HAZARD);
rooms["COC_DESERT_CAVE_EAST_HALL_2"].addFlag(GLOBAL.NOFAP);
rooms["COC_DESERT_CAVE_EAST_HALL_2"].addFlag(GLOBAL.CAVE);

rooms["COC_DESERT_CAVE_CUM_WITCH_BEDROOM"] = new RoomClass(this);
rooms["COC_DESERT_CAVE_CUM_WITCH_BEDROOM"].description = "As soon as you brush back the curtain, you're assaulted by a pungent, salty smell.  It almost reminds you of tepid ocean water... or cum.  Regardless, you force your way in and take a look around.  This area has all the furnishings of a small domicile and comes complete with a solid oak bed and mattress.  The mattress and sheets seem to be cared for with immaculate precision, perhaps magically aided.  There is a simple dresser here, and though it looks to have been fashioned by crude tools, the wood looks sturdy and serviceable.  All of the drawers are closed, of course.  A few books sit on a nearby table, but it's obvious they're written in a language beyond your comprehension.  Whoever wrote them either did so in a different tongue or a magical language that would take years to decipher.  A thick curtain walls this chamber off from the eastern warrens' main hall, to the north.  To the west, there is a thinner, gauzy sheet hanging from an opening in the rock - likely leading to a similar room.";
rooms["COC_DESERT_CAVE_CUM_WITCH_BEDROOM"].moveMinutes = 1;
rooms["COC_DESERT_CAVE_CUM_WITCH_BEDROOM"].roomName = "CUM WITCH\nBEDROOM";
rooms["COC_DESERT_CAVE_CUM_WITCH_BEDROOM"].planet = "DESERT CAVE";
rooms["COC_DESERT_CAVE_CUM_WITCH_BEDROOM"].system = "PLANET: MARETH";
rooms["COC_DESERT_CAVE_CUM_WITCH_BEDROOM"].northExit = "COC_DESERT_CAVE_EAST_HALL_2";
rooms["COC_DESERT_CAVE_CUM_WITCH_BEDROOM"].westExit = "COC_DESERT_CAVE_CUM_WITCH_OFFICE";
rooms["COC_DESERT_CAVE_CUM_WITCH_BEDROOM"].addFlag(GLOBAL.INDOOR);
rooms["COC_DESERT_CAVE_CUM_WITCH_BEDROOM"].addFlag(GLOBAL.HAZARD);
rooms["COC_DESERT_CAVE_CUM_WITCH_BEDROOM"].addFlag(GLOBAL.NOFAP);
rooms["COC_DESERT_CAVE_CUM_WITCH_BEDROOM"].addFlag(GLOBAL.CAVE);

rooms["COC_DESERT_CAVE_CUM_WITCH_OFFICE"] = new RoomClass(this);
rooms["COC_DESERT_CAVE_CUM_WITCH_OFFICE"].moveMinutes = 1;
rooms["COC_DESERT_CAVE_CUM_WITCH_OFFICE"].roomName = "CUM WITCH\nOFFICE";
rooms["COC_DESERT_CAVE_CUM_WITCH_OFFICE"].planet = "DESERT CAVE";
rooms["COC_DESERT_CAVE_CUM_WITCH_OFFICE"].system = "PLANET: MARETH";
rooms["COC_DESERT_CAVE_CUM_WITCH_OFFICE"].eastExit = "COC_DESERT_CAVE_CUM_WITCH_BEDROOM";
rooms["COC_DESERT_CAVE_CUM_WITCH_OFFICE"].addFlag(GLOBAL.INDOOR);
rooms["COC_DESERT_CAVE_CUM_WITCH_OFFICE"].addFlag(GLOBAL.HAZARD);
rooms["COC_DESERT_CAVE_CUM_WITCH_OFFICE"].addFlag(GLOBAL.NOFAP);
rooms["COC_DESERT_CAVE_CUM_WITCH_OFFICE"].addFlag(GLOBAL.CAVE);
rooms["COC_DESERT_CAVE_CUM_WITCH_OFFICE"].runOnEnter = DesertCaveCumWitchOffice;

rooms["COC_DESERT_CAVE_ALTAR"] = new RoomClass(this);
rooms["COC_DESERT_CAVE_ALTAR"].description = "This chamber clearly holds some kind of important significance to the witch coven.  The floor and walls are covered in shining white, reflective tiles, and a large number of carved jugs ring the outer edge of the room.  The entire place smells faintly of milk.  Sniffing, you close in on the source of the aroma.  It's emanating from what looks like a golden well, positioned dead-center before you.  The various containers also smell faintly of the alabaster treat, and oddly, you can't catch even a single whiff of spoilage; it all smells fresh.  There must be some magic at work.  Peeping over the edge of the well, you can barely make out what seems like a sea of milk stored below: white-capped ivory waves sloshing around in a chamber so large you can't see the walls of it.  It must be preserved through magic.\n\nThere is a doorway to the south and one on the north wall.";
rooms["COC_DESERT_CAVE_ALTAR"].moveMinutes = 1;
rooms["COC_DESERT_CAVE_ALTAR"].roomName = "ALTAR";
rooms["COC_DESERT_CAVE_ALTAR"].planet = "DESERT CAVE";
rooms["COC_DESERT_CAVE_ALTAR"].system = "PLANET: MARETH";
rooms["COC_DESERT_CAVE_ALTAR"].northExit = "COC_DESERT_CAVE_THRONE";
rooms["COC_DESERT_CAVE_ALTAR"].southExit = "COC_DESERT_CAVE_COMMONS";
rooms["COC_DESERT_CAVE_ALTAR"].addFlag(GLOBAL.INDOOR);
rooms["COC_DESERT_CAVE_ALTAR"].addFlag(GLOBAL.HAZARD);
rooms["COC_DESERT_CAVE_ALTAR"].addFlag(GLOBAL.NOFAP);
rooms["COC_DESERT_CAVE_ALTAR"].addFlag(GLOBAL.CAVE);
rooms["COC_DESERT_CAVE_ALTAR"].runOnEnter = DesertCaveAltarRoom;

rooms["COC_DESERT_CAVE_THRONE"] = new RoomClass(this);
rooms["COC_DESERT_CAVE_THRONE"].moveMinutes = 1;
rooms["COC_DESERT_CAVE_THRONE"].roomName = "SAND MOTHER\nTHRONE";
rooms["COC_DESERT_CAVE_THRONE"].planet = "DESERT CAVE";
rooms["COC_DESERT_CAVE_THRONE"].system = "PLANET: MARETH";
rooms["COC_DESERT_CAVE_THRONE"].southExit = "COC_DESERT_CAVE_ALTAR";
rooms["COC_DESERT_CAVE_THRONE"].addFlag(GLOBAL.INDOOR);
rooms["COC_DESERT_CAVE_THRONE"].addFlag(GLOBAL.HAZARD);
rooms["COC_DESERT_CAVE_THRONE"].addFlag(GLOBAL.NOFAP);
rooms["COC_DESERT_CAVE_THRONE"].addFlag(GLOBAL.CAVE);
rooms["COC_DESERT_CAVE_THRONE"].runOnEnter = DesertCaveSandMotherThrone;


// DEMONIC FACTORY

rooms["COC_FACTORY_FOYER"] = new RoomClass(this);
rooms["COC_FACTORY_FOYER"].moveMinutes = 1;
rooms["COC_FACTORY_FOYER"].roomName = "FACTORY\nENTRACE";
rooms["COC_FACTORY_FOYER"].planet = "DEMONIC FACTORY";
rooms["COC_FACTORY_FOYER"].system = "PLANET: MARETH";
rooms["COC_FACTORY_FOYER"].westExit = "COC_FACTORY_BATHROOM";
rooms["COC_FACTORY_FOYER"].eastExit = "COC_FACTORY_BREAK_ROOM";
rooms["COC_FACTORY_FOYER"].northExit = "COC_FACTORY_PUMP_ROOM";
rooms["COC_FACTORY_FOYER"].addFlag(GLOBAL.INDOOR);
rooms["COC_FACTORY_FOYER"].addFlag(GLOBAL.HAZARD);
rooms["COC_FACTORY_FOYER"].addFlag(GLOBAL.NOFAP);
rooms["COC_FACTORY_FOYER"].runOnEnter = DemonFactoryFoyer;

rooms["COC_FACTORY_BREAK_ROOM"] = new RoomClass(this);
rooms["COC_FACTORY_BREAK_ROOM"].moveMinutes = 1;
rooms["COC_FACTORY_BREAK_ROOM"].roomName = "BREAK\nROOM";
rooms["COC_FACTORY_BREAK_ROOM"].planet = "DEMONIC FACTORY";
rooms["COC_FACTORY_BREAK_ROOM"].system = "PLANET: MARETH";
rooms["COC_FACTORY_BREAK_ROOM"].westExit = "COC_FACTORY_FOYER";
rooms["COC_FACTORY_BREAK_ROOM"].addFlag(GLOBAL.INDOOR);
rooms["COC_FACTORY_BREAK_ROOM"].addFlag(GLOBAL.HAZARD);
rooms["COC_FACTORY_BREAK_ROOM"].addFlag(GLOBAL.NOFAP);
rooms["COC_FACTORY_BREAK_ROOM"].runOnEnter = DemonFactoryBreakRoom;

rooms["COC_FACTORY_PUMP_ROOM"] = new RoomClass(this);
rooms["COC_FACTORY_PUMP_ROOM"].moveMinutes = 1;
rooms["COC_FACTORY_PUMP_ROOM"].roomName = "PUMP\nROOM";
rooms["COC_FACTORY_PUMP_ROOM"].planet = "DEMONIC FACTORY";
rooms["COC_FACTORY_PUMP_ROOM"].system = "PLANET: MARETH";
rooms["COC_FACTORY_PUMP_ROOM"].northExit = "COC_FACTORY_REPAIR_CLOSET";
rooms["COC_FACTORY_PUMP_ROOM"].southExit = "COC_FACTORY_FOYER";
rooms["COC_FACTORY_PUMP_ROOM"].westExit = "COC_FACTORY_MAIN_CHAMBER";
rooms["COC_FACTORY_PUMP_ROOM"].eastExit = "COC_FACTORY_FURNACE_ROOM";
rooms["COC_FACTORY_PUMP_ROOM"].addFlag(GLOBAL.INDOOR);
rooms["COC_FACTORY_PUMP_ROOM"].addFlag(GLOBAL.HAZARD);
rooms["COC_FACTORY_PUMP_ROOM"].addFlag(GLOBAL.NOFAP);
rooms["COC_FACTORY_PUMP_ROOM"].runOnEnter = DemonFactoryPumpRoom;

rooms["COC_FACTORY_FURNACE_ROOM"] = new RoomClass(this);
rooms["COC_FACTORY_FURNACE_ROOM"].moveMinutes = 1;
rooms["COC_FACTORY_FURNACE_ROOM"].roomName = "FURNACE\nROOM";
rooms["COC_FACTORY_FURNACE_ROOM"].planet = "DEMONIC FACTORY";
rooms["COC_FACTORY_FURNACE_ROOM"].system = "PLANET: MARETH";
rooms["COC_FACTORY_FURNACE_ROOM"].westExit = "COC_FACTORY_PUMP_ROOM";
rooms["COC_FACTORY_FURNACE_ROOM"].addFlag(GLOBAL.INDOOR);
rooms["COC_FACTORY_FURNACE_ROOM"].addFlag(GLOBAL.HAZARD);
rooms["COC_FACTORY_FURNACE_ROOM"].addFlag(GLOBAL.NOFAP);
rooms["COC_FACTORY_FURNACE_ROOM"].runOnEnter = DemonFactoryFurnaceRoom;

rooms["COC_FACTORY_REPAIR_CLOSET"] = new RoomClass(this);
rooms["COC_FACTORY_REPAIR_CLOSET"].moveMinutes = 1;
rooms["COC_FACTORY_REPAIR_CLOSET"].roomName = "REPAIR\nCLOSET";
rooms["COC_FACTORY_REPAIR_CLOSET"].planet = "DEMONIC FACTORY";
rooms["COC_FACTORY_REPAIR_CLOSET"].system = "PLANET: MARETH";
rooms["COC_FACTORY_REPAIR_CLOSET"].southExit = "COC_FACTORY_PUMP_ROOM";
rooms["COC_FACTORY_REPAIR_CLOSET"].addFlag(GLOBAL.INDOOR);
rooms["COC_FACTORY_REPAIR_CLOSET"].addFlag(GLOBAL.HAZARD);
rooms["COC_FACTORY_REPAIR_CLOSET"].addFlag(GLOBAL.NOFAP);
rooms["COC_FACTORY_REPAIR_CLOSET"].runOnEnter = DemonFactoryRepairCloset;

rooms["COC_FACTORY_MAIN_CHAMBER"] = new RoomClass(this);
rooms["COC_FACTORY_MAIN_CHAMBER"].moveMinutes = 1;
rooms["COC_FACTORY_MAIN_CHAMBER"].roomName = "MAIN\nCHAMBER";
rooms["COC_FACTORY_MAIN_CHAMBER"].planet = "DEMONIC FACTORY";
rooms["COC_FACTORY_MAIN_CHAMBER"].system = "PLANET: MARETH";
rooms["COC_FACTORY_MAIN_CHAMBER"].eastExit = "COC_FACTORY_PUMP_ROOM";
rooms["COC_FACTORY_MAIN_CHAMBER"].inExit = "COC_FACTORY_FOREMAN_OFFICE";
rooms["COC_FACTORY_MAIN_CHAMBER"].inText = "Up";
rooms["COC_FACTORY_MAIN_CHAMBER"].addFlag(GLOBAL.INDOOR);
rooms["COC_FACTORY_MAIN_CHAMBER"].addFlag(GLOBAL.HAZARD);
rooms["COC_FACTORY_MAIN_CHAMBER"].addFlag(GLOBAL.NOFAP);
rooms["COC_FACTORY_MAIN_CHAMBER"].runOnEnter = DemonFactoryMainChamber;

rooms["COC_FACTORY_FOREMAN_OFFICE"] = new RoomClass(this);
rooms["COC_FACTORY_FOREMAN_OFFICE"].moveMinutes = 1;
rooms["COC_FACTORY_FOREMAN_OFFICE"].roomName = "FOREMAN\nOFFICE";
rooms["COC_FACTORY_FOREMAN_OFFICE"].planet = "DEMONIC FACTORY";
rooms["COC_FACTORY_FOREMAN_OFFICE"].system = "PLANET: MARETH";
rooms["COC_FACTORY_FOREMAN_OFFICE"].southExit = "COC_FACTORY_PREMIUM_PRODUCTS";
rooms["COC_FACTORY_FOREMAN_OFFICE"].eastExit = "COC_FACTORY_CONTROL_ROOM";
rooms["COC_FACTORY_FOREMAN_OFFICE"].outExit = "COC_FACTORY_MAIN_CHAMBER";
rooms["COC_FACTORY_FOREMAN_OFFICE"].outText = "Down";
rooms["COC_FACTORY_FOREMAN_OFFICE"].addFlag(GLOBAL.INDOOR);
rooms["COC_FACTORY_FOREMAN_OFFICE"].addFlag(GLOBAL.HAZARD);
rooms["COC_FACTORY_FOREMAN_OFFICE"].addFlag(GLOBAL.NOFAP);
rooms["COC_FACTORY_FOREMAN_OFFICE"].runOnEnter = DemonFactoryForemanOffice;

rooms["COC_FACTORY_CONTROL_ROOM"] = new RoomClass(this);
rooms["COC_FACTORY_CONTROL_ROOM"].moveMinutes = 1;
rooms["COC_FACTORY_CONTROL_ROOM"].roomName = "CONTROL\nROOM";
rooms["COC_FACTORY_CONTROL_ROOM"].planet = "DEMONIC FACTORY";
rooms["COC_FACTORY_CONTROL_ROOM"].system = "PLANET: MARETH";
rooms["COC_FACTORY_CONTROL_ROOM"].westExit = "COC_FACTORY_FOREMAN_OFFICE";
rooms["COC_FACTORY_CONTROL_ROOM"].addFlag(GLOBAL.INDOOR);
rooms["COC_FACTORY_CONTROL_ROOM"].addFlag(GLOBAL.HAZARD);
rooms["COC_FACTORY_CONTROL_ROOM"].addFlag(GLOBAL.NOFAP);
rooms["COC_FACTORY_CONTROL_ROOM"].runOnEnter = DemonFactoryControlRoom;

rooms["COC_FACTORY_PREMIUM_PRODUCTS"] = new RoomClass(this);
rooms["COC_FACTORY_PREMIUM_PRODUCTS"].moveMinutes = 1;
rooms["COC_FACTORY_PREMIUM_PRODUCTS"].roomName = "PREMIUM\nPRODUCTS";
rooms["COC_FACTORY_PREMIUM_PRODUCTS"].planet = "DEMONIC FACTORY";
rooms["COC_FACTORY_PREMIUM_PRODUCTS"].system = "PLANET: MARETH";
rooms["COC_FACTORY_PREMIUM_PRODUCTS"].northExit = "COC_FACTORY_FOREMAN_OFFICE";
rooms["COC_FACTORY_PREMIUM_PRODUCTS"].addFlag(GLOBAL.INDOOR);
rooms["COC_FACTORY_PREMIUM_PRODUCTS"].addFlag(GLOBAL.HAZARD);
rooms["COC_FACTORY_PREMIUM_PRODUCTS"].addFlag(GLOBAL.NOFAP);
rooms["COC_FACTORY_PREMIUM_PRODUCTS"].runOnEnter = DemonFactoryPremiumStorage;

rooms["COC_FACTORY_BATHROOM"] = new RoomClass(this);
rooms["COC_FACTORY_BATHROOM"].moveMinutes = 1;
rooms["COC_FACTORY_BATHROOM"].roomName = "BATHROOM";
rooms["COC_FACTORY_BATHROOM"].planet = "DEMONIC FACTORY";
rooms["COC_FACTORY_BATHROOM"].system = "PLANET: MARETH";
rooms["COC_FACTORY_BATHROOM"].eastExit = "COC_FACTORY_FOYER";
rooms["COC_FACTORY_BATHROOM"].addFlag(GLOBAL.INDOOR);
rooms["COC_FACTORY_BATHROOM"].addFlag(GLOBAL.HAZARD);
rooms["COC_FACTORY_BATHROOM"].runOnEnter = DemonFactoryBathroom;

// DEEP CAVE

rooms["COC_ZETAZ_ENTRACE"] = new RoomClass(this);
rooms["COC_ZETAZ_ENTRACE"].moveMinutes = 1;
rooms["COC_ZETAZ_ENTRACE"].roomName = "CAVE\nENTRACE";
rooms["COC_ZETAZ_ENTRACE"].planet = "DEEPWOODS CAVE";
rooms["COC_ZETAZ_ENTRACE"].system = "PLANET: MARETH";
rooms["COC_ZETAZ_ENTRACE"].northExit = "COC_ZETAZ_TUNNEL";
rooms["COC_ZETAZ_ENTRACE"].addFlag(GLOBAL.OUTDOOR);
rooms["COC_ZETAZ_ENTRACE"].addFlag(GLOBAL.JUNGLE);
rooms["COC_ZETAZ_ENTRACE"].runOnEnter = ZetazCaveEntrace;

rooms["COC_ZETAZ_TUNNEL"] = new RoomClass(this);
rooms["COC_ZETAZ_TUNNEL"].moveMinutes = 1;
rooms["COC_ZETAZ_TUNNEL"].roomName = "CAVE\nTUNNEL";
rooms["COC_ZETAZ_TUNNEL"].planet = "DEEPWOODS CAVE";
rooms["COC_ZETAZ_TUNNEL"].system = "PLANET: MARETH";
rooms["COC_ZETAZ_TUNNEL"].southExit = "COC_ZETAZ_ENTRACE";
rooms["COC_ZETAZ_TUNNEL"].northExit = "COC_ZETAZ_GATHERING_HALL";
rooms["COC_ZETAZ_TUNNEL"].addFlag(GLOBAL.INDOOR);
rooms["COC_ZETAZ_TUNNEL"].addFlag(GLOBAL.HAZARD);
rooms["COC_ZETAZ_TUNNEL"].addFlag(GLOBAL.NOFAP);
rooms["COC_ZETAZ_TUNNEL"].addFlag(GLOBAL.CAVE);
rooms["COC_ZETAZ_TUNNEL"].runOnEnter = ZetazCaveTunnel;

rooms["COC_ZETAZ_GATHERING_HALL"] = new RoomClass(this);
rooms["COC_ZETAZ_GATHERING_HALL"].moveMinutes = 1;
rooms["COC_ZETAZ_GATHERING_HALL"].roomName = "GATHERING\nHALL";
rooms["COC_ZETAZ_GATHERING_HALL"].planet = "DEEPWOODS CAVE";
rooms["COC_ZETAZ_GATHERING_HALL"].system = "PLANET: MARETH";
rooms["COC_ZETAZ_GATHERING_HALL"].southExit = "COC_ZETAZ_TUNNEL";
rooms["COC_ZETAZ_GATHERING_HALL"].westExit = "COC_ZETAZ_FUNGUS_CAVERN";
rooms["COC_ZETAZ_GATHERING_HALL"].eastExit = "COC_ZETAZ_TORTURE_ROOM";
rooms["COC_ZETAZ_GATHERING_HALL"].northExit = "COC_ZETAZ_CHAMBER";
rooms["COC_ZETAZ_GATHERING_HALL"].addFlag(GLOBAL.INDOOR);
rooms["COC_ZETAZ_GATHERING_HALL"].addFlag(GLOBAL.HAZARD);
rooms["COC_ZETAZ_GATHERING_HALL"].addFlag(GLOBAL.NOFAP);
rooms["COC_ZETAZ_GATHERING_HALL"].addFlag(GLOBAL.CAVE);
rooms["COC_ZETAZ_GATHERING_HALL"].runOnEnter = ZetazCaveGatheringHall;

rooms["COC_ZETAZ_FUNGUS_CAVERN"] = new RoomClass(this);
rooms["COC_ZETAZ_FUNGUS_CAVERN"].moveMinutes = 1;
rooms["COC_ZETAZ_FUNGUS_CAVERN"].roomName = "FUNGUS\nCAVERN";
rooms["COC_ZETAZ_FUNGUS_CAVERN"].planet = "DEEPWOODS CAVE";
rooms["COC_ZETAZ_FUNGUS_CAVERN"].system = "PLANET: MARETH";
rooms["COC_ZETAZ_FUNGUS_CAVERN"].eastExit = "COC_ZETAZ_GATHERING_HALL";
rooms["COC_ZETAZ_FUNGUS_CAVERN"].addFlag(GLOBAL.INDOOR);
rooms["COC_ZETAZ_FUNGUS_CAVERN"].addFlag(GLOBAL.HAZARD);
rooms["COC_ZETAZ_FUNGUS_CAVERN"].addFlag(GLOBAL.NOFAP);
rooms["COC_ZETAZ_FUNGUS_CAVERN"].addFlag(GLOBAL.CAVE);
rooms["COC_ZETAZ_FUNGUS_CAVERN"].runOnEnter = ZetazCaveFungusCavern;

rooms["COC_ZETAZ_TORTURE_ROOM"] = new RoomClass(this);
rooms["COC_ZETAZ_TORTURE_ROOM"].moveMinutes = 1;
rooms["COC_ZETAZ_TORTURE_ROOM"].roomName = "TORTURE\nROOM";
rooms["COC_ZETAZ_TORTURE_ROOM"].planet = "DEEPWOODS CAVE";
rooms["COC_ZETAZ_TORTURE_ROOM"].system = "PLANET: MARETH";
rooms["COC_ZETAZ_TORTURE_ROOM"].westExit = "COC_ZETAZ_GATHERING_HALL";
rooms["COC_ZETAZ_TORTURE_ROOM"].northExit = "COC_ZETAZ_SECRET_PASSAGE";
rooms["COC_ZETAZ_TORTURE_ROOM"].addFlag(GLOBAL.INDOOR);
rooms["COC_ZETAZ_TORTURE_ROOM"].addFlag(GLOBAL.HAZARD);
rooms["COC_ZETAZ_TORTURE_ROOM"].addFlag(GLOBAL.NOFAP);
rooms["COC_ZETAZ_TORTURE_ROOM"].addFlag(GLOBAL.CAVE);
rooms["COC_ZETAZ_TORTURE_ROOM"].runOnEnter = ZetazCaveTortureRoom;

rooms["COC_ZETAZ_SECRET_PASSAGE"] = new RoomClass(this);
rooms["COC_ZETAZ_SECRET_PASSAGE"].moveMinutes = 1;
rooms["COC_ZETAZ_SECRET_PASSAGE"].roomName = "SECRET\nPASSAGE";
rooms["COC_ZETAZ_SECRET_PASSAGE"].planet = "DEEPWOODS CAVE";
rooms["COC_ZETAZ_SECRET_PASSAGE"].system = "PLANET: MARETH";
rooms["COC_ZETAZ_SECRET_PASSAGE"].westExit = "COC_ZETAZ_CHAMBER";
rooms["COC_ZETAZ_SECRET_PASSAGE"].southExit = "COC_ZETAZ_TORTURE_ROOM";
rooms["COC_ZETAZ_SECRET_PASSAGE"].addFlag(GLOBAL.INDOOR);
rooms["COC_ZETAZ_SECRET_PASSAGE"].addFlag(GLOBAL.HAZARD);
rooms["COC_ZETAZ_SECRET_PASSAGE"].addFlag(GLOBAL.NOFAP);
rooms["COC_ZETAZ_SECRET_PASSAGE"].addFlag(GLOBAL.CAVE);
rooms["COC_ZETAZ_SECRET_PASSAGE"].runOnEnter = ZetazCaveSecretPassage;

rooms["COC_ZETAZ_CHAMBER"] = new RoomClass(this);
rooms["COC_ZETAZ_CHAMBER"].moveMinutes = 1;
rooms["COC_ZETAZ_CHAMBER"].roomName = "ZETAZ\nCHAMBER";
rooms["COC_ZETAZ_CHAMBER"].planet = "DEEPWOODS CAVE";
rooms["COC_ZETAZ_CHAMBER"].system = "PLANET: MARETH";
rooms["COC_ZETAZ_CHAMBER"].eastExit = "COC_ZETAZ_SECRET_PASSAGE";
rooms["COC_ZETAZ_CHAMBER"].southExit = "COC_ZETAZ_GATHERING_HALL";
rooms["COC_ZETAZ_CHAMBER"].addFlag(GLOBAL.INDOOR);
rooms["COC_ZETAZ_CHAMBER"].addFlag(GLOBAL.HAZARD);
rooms["COC_ZETAZ_CHAMBER"].addFlag(GLOBAL.NOFAP);
rooms["COC_ZETAZ_CHAMBER"].addFlag(GLOBAL.CAVE);
rooms["COC_ZETAZ_CHAMBER"].runOnEnter = ZetazCaveZetazChamber;