import classes.RoomClass;
import classes.GLOBAL;
import classes.Util.*;
import classes.Engine.Interfaces.*;
import classes.Engine.Utility.*;

//public static const INDOOR:int                                 = 0;
//public static const OUTDOOR:int                                = 1;
//public static const BED:int                                    = 2;
//public static const COMMERCE:int							   = 3;
//public static const BAR:int									   = 4;
//public static const NPC:int									   = 5;
//public static const MEDICAL:int								   = 6;
//public static const SHIPHANGAR:int							   = 7;
//public static const QUEST:int								   = 8;
//public static const OBJECTIVE:int						       = 9;
//public static const HAZARD:int								   = 10;
//public static const NOFAP:int 								   = 11;
//public static const LIFTUP:int 								   = 12;
//public static const LIFTDOWN:int 								= 13;
//public static const TAXI:int    								= 14;
//public static const PUBLIC:int 									= 15;
//public static const PRIVATE:int									= 16;
//public static const FAPPING_ILLEGAL:int							= 17;
//public static const NUDITY_ILLEGAL:int							= 18;
//public static const CAVE:int									= 19;
//public static const FOREST:int									= 20;
//public static const JUNGLE:int									= 21;
//public static const DESERT:int									= 22;
//public static const PLANE:int									= 23;
//public static const PLANT_BULB:int								= 24;

//private static const DUNGEON_HEL_GUARD_HALL:int		= 17;
//private static const DUNGEON_HEL_WINE_CELLAR:int	= 18;
//private static const DUNGEON_HEL_STAIR_WELL:int		= 19;
//private static const DUNGEON_HEL_DUNGEON:int		= 20;
//private static const DUNGEON_HEL_MEZZANINE:int		= 21;
//private static const DUNGEON_HEL_THRONE_ROOM:int	= 22;

rooms["COC PHOENIX ENTRACE"] = new RoomClass(this);
rooms["COC PHOENIX ENTRACE"].description = "You are standing just outside of the tower.";
rooms["COC PHOENIX ENTRACE"].moveMinutes = 2;
rooms["COC PHOENIX ENTRACE"].roomName = "\nENTRACE";
rooms["COC PHOENIX ENTRACE"].planet = "PHOENIX TOWER";
rooms["COC PHOENIX ENTRACE"].system = "PLANET: MARETH";
rooms["COC PHOENIX ENTRACE"].westExit = "COC PHOENIX GUARD HALL";
rooms["COC PHOENIX ENTRACE"].addFlag(GLOBAL.OUTDOOR);
rooms["COC PHOENIX ENTRACE"].addFlag(GLOBAL.PRIVATE);
rooms["COC PHOENIX ENTRACE"].addFlag(GLOBAL.HAZARD);
rooms["COC PHOENIX ENTRACE"].runOnEnter = PhoenixTowerEntranceRoomFunc;

rooms["COC PHOENIX GUARD HALL"] = new RoomClass(this);
rooms["COC PHOENIX GUARD HALL"].moveMinutes = 2;
rooms["COC PHOENIX GUARD HALL"].roomName = "GUARD\nHALL";
rooms["COC PHOENIX GUARD HALL"].planet = "PHOENIX TOWER";
rooms["COC PHOENIX GUARD HALL"].system = "PLANET: MARETH";
rooms["COC PHOENIX GUARD HALL"].westExit = "COC PHOENIX STAIR WELL";
rooms["COC PHOENIX GUARD HALL"].eastExit = "COC PHOENIX ENTRACE";
rooms["COC PHOENIX GUARD HALL"].southExit = "COC PHOENIX WINE CELLAR";
rooms["COC PHOENIX GUARD HALL"].addFlag(GLOBAL.INDOOR);
rooms["COC PHOENIX GUARD HALL"].addFlag(GLOBAL.PRIVATE);
rooms["COC PHOENIX GUARD HALL"].addFlag(GLOBAL.HAZARD);
rooms["COC PHOENIX GUARD HALL"].addFlag(GLOBAL.NOFAP);
rooms["COC PHOENIX GUARD HALL"].runOnEnter = PhoenixTowerGuardHallRoomFunc;

rooms["COC PHOENIX WINE CELLAR"] = new RoomClass(this);
rooms["COC PHOENIX WINE CELLAR"].moveMinutes = 2;
rooms["COC PHOENIX WINE CELLAR"].roomName = "GUARD\nHALL";
rooms["COC PHOENIX WINE CELLAR"].planet = "PHOENIX TOWER";
rooms["COC PHOENIX WINE CELLAR"].system = "PLANET: MARETH";
rooms["COC PHOENIX WINE CELLAR"].northExit = "COC PHOENIX GUARD HALL";
rooms["COC PHOENIX WINE CELLAR"].addFlag(GLOBAL.CAVE);
rooms["COC PHOENIX WINE CELLAR"].addFlag(GLOBAL.PRIVATE);
rooms["COC PHOENIX WINE CELLAR"].runOnEnter = PhoenixTowerCellarRoomFunc;

rooms["COC PHOENIX STAIR WELL"] = new RoomClass(this);
rooms["COC PHOENIX STAIR WELL"].moveMinutes = 2;
rooms["COC PHOENIX STAIR WELL"].roomName = "GUARD\nHALL";
rooms["COC PHOENIX STAIR WELL"].planet = "PHOENIX TOWER";
rooms["COC PHOENIX STAIR WELL"].system = "PLANET: MARETH";
rooms["COC PHOENIX STAIR WELL"].northExit = "COC PHOENIX MEZZANINE";
rooms["COC PHOENIX STAIR WELL"].eastExit = "COC PHOENIX GUARD HALL";
rooms["COC PHOENIX STAIR WELL"].southExit = "COC PHOENIX DUNGEON";
rooms["COC PHOENIX STAIR WELL"].addFlag(GLOBAL.INDOOR);
rooms["COC PHOENIX STAIR WELL"].addFlag(GLOBAL.PRIVATE);
rooms["COC PHOENIX STAIR WELL"].addFlag(GLOBAL.HAZARD);
rooms["COC PHOENIX STAIR WELL"].addFlag(GLOBAL.NOFAP);
rooms["COC PHOENIX STAIR WELL"].runOnEnter = PhoenixTowerStairwellRoomFunc;

rooms["COC PHOENIX DUNGEON"] = new RoomClass(this);
rooms["COC PHOENIX DUNGEON"].moveMinutes = 2;
rooms["COC PHOENIX DUNGEON"].roomName = "GUARD\nHALL";
rooms["COC PHOENIX DUNGEON"].planet = "PHOENIX TOWER";
rooms["COC PHOENIX DUNGEON"].system = "PLANET: MARETH";
rooms["COC PHOENIX DUNGEON"].northExit = "COC PHOENIX STAIR WELL";
rooms["COC PHOENIX DUNGEON"].addFlag(GLOBAL.INDOOR);
rooms["COC PHOENIX DUNGEON"].addFlag(GLOBAL.PRIVATE);
rooms["COC PHOENIX DUNGEON"].addFlag(GLOBAL.HAZARD);
rooms["COC PHOENIX DUNGEON"].addFlag(GLOBAL.NOFAP);
rooms["COC PHOENIX DUNGEON"].runOnEnter = PhoenixTowerDungeonRoomFunc;

rooms["COC PHOENIX MEZZANINE"] = new RoomClass(this);
rooms["COC PHOENIX MEZZANINE"].moveMinutes = 2;
rooms["COC PHOENIX MEZZANINE"].roomName = "GUARD\nHALL";
rooms["COC PHOENIX MEZZANINE"].planet = "PHOENIX TOWER";
rooms["COC PHOENIX MEZZANINE"].system = "PLANET: MARETH";
rooms["COC PHOENIX MEZZANINE"].northExit = "COC PHOENIX THRONE ROOM";
rooms["COC PHOENIX MEZZANINE"].southExit = "COC PHOENIX STAIR WELL";
rooms["COC PHOENIX MEZZANINE"].addFlag(GLOBAL.INDOOR);
rooms["COC PHOENIX MEZZANINE"].addFlag(GLOBAL.PRIVATE);
rooms["COC PHOENIX MEZZANINE"].addFlag(GLOBAL.HAZARD);
rooms["COC PHOENIX MEZZANINE"].addFlag(GLOBAL.NOFAP);
rooms["COC PHOENIX MEZZANINE"].runOnEnter = PhoenixTowerMezzanineRoomFunc;

rooms["COC PHOENIX THRONE ROOM"] = new RoomClass(this);
rooms["COC PHOENIX THRONE ROOM"].moveMinutes = 2;
rooms["COC PHOENIX THRONE ROOM"].roomName = "GUARD\nHALL";
rooms["COC PHOENIX THRONE ROOM"].planet = "PHOENIX TOWER";
rooms["COC PHOENIX THRONE ROOM"].system = "PLANET: MARETH";
rooms["COC PHOENIX THRONE ROOM"].southExit = "COC PHOENIX MEZZANINE";
rooms["COC PHOENIX THRONE ROOM"].addFlag(GLOBAL.INDOOR);
rooms["COC PHOENIX THRONE ROOM"].addFlag(GLOBAL.PRIVATE);
rooms["COC PHOENIX THRONE ROOM"].addFlag(GLOBAL.HAZARD);
rooms["COC PHOENIX THRONE ROOM"].addFlag(GLOBAL.NOFAP);
rooms["COC PHOENIX THRONE ROOM"].runOnEnter = PhoenixTowerThroneRoomRoomFunc;